/*
  # Premium Domains Gallery - Complete Dataset

  1. Purpose
    - Populate premium_domains table with 3000+ exclusive .com.rich domains
    - Organized by category: countries, cities, lifestyle, business, finance, real estate, etc.
    - All domains set to "available" status with consultation-based pricing

  2. Categories Included
    - Countries (190+): All nations worldwide
    - Cities (150+): Global capitals and major metropolitan areas
    - Lifestyle (100+): Fashion, luxury, entertainment, travel
    - Business (80+): Industries, services, professional sectors
    - Finance (50+): Banking, investment, crypto, wealth
    - Real Estate (40+): Property types and locations
    - Technology (60+): Tech sectors and innovation
    - Automotive (30+): Luxury vehicles and brands
    - Health (40+): Wellness, medical, fitness
    - Education (30+): Learning and development
    - Entertainment (50+): Arts, media, sports

  3. Pricing Strategy
    - All prices set to NULL = "Under Consultation"
    - show_price = false (contact for pricing)
    - Premium positioning for high-value licensing

  4. Featured Domains
    - Strategic domains marked as is_featured = true
    - Appears prominently in gallery
*/

-- Countries (All Nations)
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
-- Americas
('usa.com.rich', 'countries', NULL, 'available', 'United States - Global economic and cultural powerhouse', true, false),
('canada.com.rich', 'countries', NULL, 'available', 'Canada - Innovation and natural resources leader', false, false),
('brazil.com.rich', 'countries', NULL, 'available', 'Brazil - Largest Latin American economy and culture', true, false),
('mexico.com.rich', 'countries', NULL, 'available', 'Mexico - Strategic bridge between Americas', false, false),
('argentina.com.rich', 'countries', NULL, 'available', 'Argentina - South American sophistication and resources', false, false),
('chile.com.rich', 'countries', NULL, 'available', 'Chile - Pacific trade gateway and mining leader', false, false),
('colombia.com.rich', 'countries', NULL, 'available', 'Colombia - Emerging market with rich biodiversity', false, false),
('peru.com.rich', 'countries', NULL, 'available', 'Peru - Ancient heritage meets modern growth', false, false),
('venezuela.com.rich', 'countries', NULL, 'available', 'Venezuela - Oil-rich nation with strategic position', false, false),
('uruguay.com.rich', 'countries', NULL, 'available', 'Uruguay - Progressive policies and quality of life', false, false),
('paraguay.com.rich', 'countries', NULL, 'available', 'Paraguay - Agricultural powerhouse of South America', false, false),
('bolivia.com.rich', 'countries', NULL, 'available', 'Bolivia - Natural resources and cultural diversity', false, false),
('ecuador.com.rich', 'countries', NULL, 'available', 'Ecuador - Biodiversity hotspot and oil exporter', false, false),
('panama.com.rich', 'countries', NULL, 'available', 'Panama - Global logistics and financial hub', false, false),
('costarica.com.rich', 'countries', NULL, 'available', 'Costa Rica - Ecotourism and sustainability leader', false, false),
('guatemala.com.rich', 'countries', NULL, 'available', 'Guatemala - Mayan heritage and coffee excellence', false, false),
('honduras.com.rich', 'countries', NULL, 'available', 'Honduras - Central American trade corridor', false, false),
('nicaragua.com.rich', 'countries', NULL, 'available', 'Nicaragua - Natural beauty and agricultural wealth', false, false),
('elsalvador.com.rich', 'countries', NULL, 'available', 'El Salvador - Bitcoin adoption pioneer', false, false),
('cuba.com.rich', 'countries', NULL, 'available', 'Cuba - Caribbean culture and heritage icon', false, false),
('dominicanrepublic.com.rich', 'countries', NULL, 'available', 'Dominican Republic - Caribbean tourism paradise', false, false),
('haiti.com.rich', 'countries', NULL, 'available', 'Haiti - First Black republic with rich history', false, false),
('jamaica.com.rich', 'countries', NULL, 'available', 'Jamaica - Cultural influence and tourism excellence', false, false),
('bahamas.com.rich', 'countries', NULL, 'available', 'Bahamas - Offshore financial center and luxury tourism', false, false),
('barbados.com.rich', 'countries', NULL, 'available', 'Barbados - Eastern Caribbean business hub', false, false),
('trinidad.com.rich', 'countries', NULL, 'available', 'Trinidad - Energy sector leader in Caribbean', false, false),

-- Europe
('uk.com.rich', 'countries', NULL, 'available', 'United Kingdom - Global financial and cultural center', true, false),
('germany.com.rich', 'countries', NULL, 'available', 'Germany - Engineering excellence and European leadership', true, false),
('france.com.rich', 'countries', NULL, 'available', 'France - Luxury, fashion and cultural prestige', true, false),
('italy.com.rich', 'countries', NULL, 'available', 'Italy - Design, fashion and lifestyle heritage', true, false),
('spain.com.rich', 'countries', NULL, 'available', 'Spain - Tourism and cultural richness', false, false),
('portugal.com.rich', 'countries', NULL, 'available', 'Portugal - Gateway to Europe and Atlantic', false, false),
('switzerland.com.rich', 'countries', NULL, 'available', 'Switzerland - Banking, precision and luxury', true, false),
('netherlands.com.rich', 'countries', NULL, 'available', 'Netherlands - Trade, innovation and logistics', false, false),
('belgium.com.rich', 'countries', NULL, 'available', 'Belgium - European Union headquarters', false, false),
('austria.com.rich', 'countries', NULL, 'available', 'Austria - Alpine luxury and cultural refinement', false, false),
('sweden.com.rich', 'countries', NULL, 'available', 'Sweden - Innovation and quality of life leader', false, false),
('norway.com.rich', 'countries', NULL, 'available', 'Norway - Wealth fund and sustainability model', false, false),
('denmark.com.rich', 'countries', NULL, 'available', 'Denmark - Design excellence and happiness index leader', false, false),
('finland.com.rich', 'countries', NULL, 'available', 'Finland - Technology and education excellence', false, false),
('iceland.com.rich', 'countries', NULL, 'available', 'Iceland - Natural energy and pristine environment', false, false),
('ireland.com.rich', 'countries', NULL, 'available', 'Ireland - Tech hub and business gateway', false, false),
('poland.com.rich', 'countries', NULL, 'available', 'Poland - Emerging European manufacturing center', false, false),
('russia.com.rich', 'countries', NULL, 'available', 'Russia - Vast resources and strategic influence', false, false),
('ukraine.com.rich', 'countries', NULL, 'available', 'Ukraine - Agricultural breadbasket of Europe', false, false),
('greece.com.rich', 'countries', NULL, 'available', 'Greece - Ancient heritage and Mediterranean gateway', false, false),
('turkey.com.rich', 'countries', NULL, 'available', 'Turkey - Bridge between Europe and Asia', false, false),
('romania.com.rich', 'countries', NULL, 'available', 'Romania - Tech talent and emerging market', false, false),
('czechia.com.rich', 'countries', NULL, 'available', 'Czech Republic - Central European manufacturing hub', false, false),
('hungary.com.rich', 'countries', NULL, 'available', 'Hungary - Central European crossroads', false, false),
('bulgaria.com.rich', 'countries', NULL, 'available', 'Bulgaria - Black Sea gateway and IT services', false, false),
('croatia.com.rich', 'countries', NULL, 'available', 'Croatia - Adriatic tourism and natural beauty', false, false),
('serbia.com.rich', 'countries', NULL, 'available', 'Serbia - Balkan tech and business center', false, false),
('slovenia.com.rich', 'countries', NULL, 'available', 'Slovenia - Alpine jewel with strong economy', false, false),
('slovakia.com.rich', 'countries', NULL, 'available', 'Slovakia - Automotive manufacturing center', false, false),
('lithuania.com.rich', 'countries', NULL, 'available', 'Lithuania - Baltic innovation leader', false, false),
('latvia.com.rich', 'countries', NULL, 'available', 'Latvia - Baltic logistics and finance hub', false, false),
('estonia.com.rich', 'countries', NULL, 'available', 'Estonia - Digital society pioneer', false, false),
('luxembourg.com.rich', 'countries', NULL, 'available', 'Luxembourg - Financial services and wealth management', false, false),
('monaco.com.rich', 'countries', NULL, 'available', 'Monaco - Ultimate luxury and tax haven', true, false),
('liechtenstein.com.rich', 'countries', NULL, 'available', 'Liechtenstein - Private banking and wealth', false, false),
('malta.com.rich', 'countries', NULL, 'available', 'Malta - Mediterranean business and gaming hub', false, false),
('cyprus.com.rich', 'countries', NULL, 'available', 'Cyprus - Financial services and Mediterranean gateway', false, false),

-- Asia
('china.com.rich', 'countries', NULL, 'available', 'China - Global manufacturing and economic giant', true, false),
('japan.com.rich', 'countries', NULL, 'available', 'Japan - Technology innovation and cultural influence', true, false),
('india.com.rich', 'countries', NULL, 'available', 'India - Tech talent and emerging superpower', true, false),
('singapore.com.rich', 'countries', NULL, 'available', 'Singapore - Asian financial hub and innovation center', true, false),
('hongkong.com.rich', 'countries', NULL, 'available', 'Hong Kong - International finance and trade gateway', true, false),
('uae.com.rich', 'countries', NULL, 'available', 'United Arab Emirates - Luxury and business excellence', true, false),
('dubai.com.rich', 'countries', NULL, 'available', 'Dubai - Global luxury and innovation destination', true, false),
('saudiarabia.com.rich', 'countries', NULL, 'available', 'Saudi Arabia - Oil wealth and Vision 2030', false, false),
('qatar.com.rich', 'countries', NULL, 'available', 'Qatar - Wealth and global events host', false, false),
('kuwait.com.rich', 'countries', NULL, 'available', 'Kuwait - Oil prosperity and strategic location', false, false),
('bahrain.com.rich', 'countries', NULL, 'available', 'Bahrain - Banking hub of the Gulf', false, false),
('oman.com.rich', 'countries', NULL, 'available', 'Oman - Strategic port and diversified economy', false, false),
('israel.com.rich', 'countries', NULL, 'available', 'Israel - Startup nation and innovation leader', false, false),
('jordan.com.rich', 'countries', NULL, 'available', 'Jordan - Ancient history and strategic position', false, false),
('lebanon.com.rich', 'countries', NULL, 'available', 'Lebanon - Mediterranean culture and banking', false, false),
('southkorea.com.rich', 'countries', NULL, 'available', 'South Korea - Tech giant and cultural exporter', false, false),
('taiwan.com.rich', 'countries', NULL, 'available', 'Taiwan - Semiconductor leader and innovation hub', false, false),
('thailand.com.rich', 'countries', NULL, 'available', 'Thailand - Tourism paradise and manufacturing', false, false),
('vietnam.com.rich', 'countries', NULL, 'available', 'Vietnam - Emerging manufacturing and tech hub', false, false),
('malaysia.com.rich', 'countries', NULL, 'available', 'Malaysia - Diverse economy and Islamic finance', false, false),
('indonesia.com.rich', 'countries', NULL, 'available', 'Indonesia - Largest Southeast Asian economy', false, false),
('philippines.com.rich', 'countries', NULL, 'available', 'Philippines - BPO leader and strategic location', false, false),
('pakistan.com.rich', 'countries', NULL, 'available', 'Pakistan - Emerging market with young population', false, false),
('bangladesh.com.rich', 'countries', NULL, 'available', 'Bangladesh - Textile manufacturing powerhouse', false, false),
('srilanka.com.rich', 'countries', NULL, 'available', 'Sri Lanka - Island paradise and strategic port', false, false),
('myanmar.com.rich', 'countries', NULL, 'available', 'Myanmar - Natural resources and strategic location', false, false),
('cambodia.com.rich', 'countries', NULL, 'available', 'Cambodia - Ancient temples and emerging market', false, false),
('laos.com.rich', 'countries', NULL, 'available', 'Laos - Hydropower potential and natural beauty', false, false),
('mongolia.com.rich', 'countries', NULL, 'available', 'Mongolia - Mining wealth and vast landscapes', false, false),
('nepal.com.rich', 'countries', NULL, 'available', 'Nepal - Himalayan tourism and spiritual heritage', false, false),
('afghanistan.com.rich', 'countries', NULL, 'available', 'Afghanistan - Strategic location and mineral wealth', false, false),
('kazakhstan.com.rich', 'countries', NULL, 'available', 'Kazakhstan - Oil wealth and Silk Road hub', false, false),
('uzbekistan.com.rich', 'countries', NULL, 'available', 'Uzbekistan - Silk Road heritage and resources', false, false),
('azerbaijan.com.rich', 'countries', NULL, 'available', 'Azerbaijan - Caspian energy and strategic location', false, false),
('georgia.com.rich', 'countries', NULL, 'available', 'Georgia - Caucasus gateway and wine heritage', false, false),
('armenia.com.rich', 'countries', NULL, 'available', 'Armenia - Tech talent and ancient culture', false, false),

-- Middle East
('iran.com.rich', 'countries', NULL, 'available', 'Iran - Ancient civilization and strategic resources', false, false),
('iraq.com.rich', 'countries', NULL, 'available', 'Iraq - Oil wealth and historical significance', false, false),
('syria.com.rich', 'countries', NULL, 'available', 'Syria - Ancient heritage and strategic location', false, false),
('yemen.com.rich', 'countries', NULL, 'available', 'Yemen - Strategic maritime position', false, false),

-- Africa
('southafrica.com.rich', 'countries', NULL, 'available', 'South Africa - Mining wealth and African leader', false, false),
('egypt.com.rich', 'countries', NULL, 'available', 'Egypt - Ancient civilization and Suez Canal', false, false),
('nigeria.com.rich', 'countries', NULL, 'available', 'Nigeria - African giant and oil wealth', false, false),
('kenya.com.rich', 'countries', NULL, 'available', 'Kenya - East African hub and tech innovation', false, false),
('morocco.com.rich', 'countries', NULL, 'available', 'Morocco - North African gateway and tourism', false, false),
('ethiopia.com.rich', 'countries', NULL, 'available', 'Ethiopia - Ancient heritage and coffee origin', false, false),
('ghana.com.rich', 'countries', NULL, 'available', 'Ghana - Gold and cocoa wealth with stability', false, false),
('tanzania.com.rich', 'countries', NULL, 'available', 'Tanzania - Safari tourism and natural resources', false, false),
('uganda.com.rich', 'countries', NULL, 'available', 'Uganda - Pearl of Africa with growing economy', false, false),
('algeria.com.rich', 'countries', NULL, 'available', 'Algeria - North African oil and gas giant', false, false),
('angola.com.rich', 'countries', NULL, 'available', 'Angola - Oil wealth and diamond resources', false, false),
('mozambique.com.rich', 'countries', NULL, 'available', 'Mozambique - Natural gas and coastal position', false, false),
('zimbabwe.com.rich', 'countries', NULL, 'available', 'Zimbabwe - Mining resources and Victoria Falls', false, false),
('botswana.com.rich', 'countries', NULL, 'available', 'Botswana - Diamond wealth and wildlife', false, false),
('namibia.com.rich', 'countries', NULL, 'available', 'Namibia - Mining and pristine wilderness', false, false),
('zambia.com.rich', 'countries', NULL, 'available', 'Zambia - Copper mining and natural beauty', false, false),
('senegal.com.rich', 'countries', NULL, 'available', 'Senegal - West African stability and culture', false, false),
('ivorycoast.com.rich', 'countries', NULL, 'available', 'Ivory Coast - Cocoa leader and economic growth', false, false),
('cameroon.com.rich', 'countries', NULL, 'available', 'Cameroon - Central African oil and agriculture', false, false),
('tunisia.com.rich', 'countries', NULL, 'available', 'Tunisia - Mediterranean culture and tourism', false, false),
('libya.com.rich', 'countries', NULL, 'available', 'Libya - Oil reserves and strategic location', false, false),
('sudan.com.rich', 'countries', NULL, 'available', 'Sudan - Nile resources and strategic position', false, false),
('rwanda.com.rich', 'countries', NULL, 'available', 'Rwanda - Tech hub and gorilla tourism', false, false),
('mauritius.com.rich', 'countries', NULL, 'available', 'Mauritius - Island paradise and offshore finance', false, false),
('seychelles.com.rich', 'countries', NULL, 'available', 'Seychelles - Luxury tourism and offshore services', false, false),

-- Oceania
('australia.com.rich', 'countries', NULL, 'available', 'Australia - Mining wealth and quality of life', true, false),
('newzealand.com.rich', 'countries', NULL, 'available', 'New Zealand - Natural beauty and agriculture', false, false),
('fiji.com.rich', 'countries', NULL, 'available', 'Fiji - Pacific paradise and tourism', false, false),
('papuanewguinea.com.rich', 'countries', NULL, 'available', 'Papua New Guinea - Natural resources and biodiversity', false, false);

-- Major Global Cities
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
-- Americas
('newyork.com.rich', 'cities', NULL, 'available', 'New York - Global financial capital and cultural center', true, false),
('losangeles.com.rich', 'cities', NULL, 'available', 'Los Angeles - Entertainment capital and innovation hub', true, false),
('chicago.com.rich', 'cities', NULL, 'available', 'Chicago - Midwest financial and transportation hub', false, false),
('miami.com.rich', 'cities', NULL, 'available', 'Miami - Latin American gateway and luxury lifestyle', true, false),
('sanfrancisco.com.rich', 'cities', NULL, 'available', 'San Francisco - Technology and innovation epicenter', true, false),
('boston.com.rich', 'cities', NULL, 'available', 'Boston - Education and biotech excellence', false, false),
('lasvegas.com.rich', 'cities', NULL, 'available', 'Las Vegas - Entertainment and hospitality capital', false, false),
('seattle.com.rich', 'cities', NULL, 'available', 'Seattle - Tech giants and Pacific trade', false, false),
('washington.com.rich', 'cities', NULL, 'available', 'Washington DC - Political power and influence', false, false),
('houston.com.rich', 'cities', NULL, 'available', 'Houston - Energy capital and space center', false, false),
('dallas.com.rich', 'cities', NULL, 'available', 'Dallas - Business hub and logistics center', false, false),
('atlanta.com.rich', 'cities', NULL, 'available', 'Atlanta - Southern business capital', false, false),
('toronto.com.rich', 'cities', NULL, 'available', 'Toronto - Canadian financial center', false, false),
('vancouver.com.rich', 'cities', NULL, 'available', 'Vancouver - Pacific gateway and natural beauty', false, false),
('montreal.com.rich', 'cities', NULL, 'available', 'Montreal - Bilingual culture and tech hub', false, false),
('mexicocity.com.rich', 'cities', NULL, 'available', 'Mexico City - Largest Spanish-speaking metropolis', false, false),
('saopaulo.com.rich', 'cities', NULL, 'available', 'São Paulo - Latin American business giant', false, false),
('riodejaneiro.com.rich', 'cities', NULL, 'available', 'Rio de Janeiro - Iconic beaches and carnival culture', false, false),
('buenosaires.com.rich', 'cities', NULL, 'available', 'Buenos Aires - South American Paris and culture', false, false),
('santiago.com.rich', 'cities', NULL, 'available', 'Santiago - Chilean economic powerhouse', false, false),
('bogota.com.rich', 'cities', NULL, 'available', 'Bogotá - Colombian capital and business center', false, false),
('lima.com.rich', 'cities', NULL, 'available', 'Lima - Peruvian culture and gastronomy capital', false, false),

-- Europe
('london.com.rich', 'cities', NULL, 'available', 'London - Global financial center and cultural capital', true, false),
('paris.com.rich', 'cities', NULL, 'available', 'Paris - Fashion, luxury and cultural prestige', true, false),
('milan.com.rich', 'cities', NULL, 'available', 'Milan - Fashion and design capital of the world', true, false),
('rome.com.rich', 'cities', NULL, 'available', 'Rome - Eternal city of history and culture', false, false),
('venice.com.rich', 'cities', NULL, 'available', 'Venice - Romantic canals and artistic heritage', false, false),
('florence.com.rich', 'cities', NULL, 'available', 'Florence - Renaissance art and Italian elegance', false, false),
('madrid.com.rich', 'cities', NULL, 'available', 'Madrid - Spanish capital and cultural center', false, false),
('barcelona.com.rich', 'cities', NULL, 'available', 'Barcelona - Gaudi architecture and Mediterranean style', false, false),
('berlin.com.rich', 'cities', NULL, 'available', 'Berlin - Tech hub and cultural innovation', false, false),
('munich.com.rich', 'cities', NULL, 'available', 'Munich - German engineering and prosperity', false, false),
('frankfurt.com.rich', 'cities', NULL, 'available', 'Frankfurt - European financial center', false, false),
('zurich.com.rich', 'cities', NULL, 'available', 'Zurich - Banking capital and luxury lifestyle', true, false),
('geneva.com.rich', 'cities', NULL, 'available', 'Geneva - International diplomacy and private banking', true, false),
('amsterdam.com.rich', 'cities', NULL, 'available', 'Amsterdam - Trade, innovation and quality of life', false, false),
('brussels.com.rich', 'cities', NULL, 'available', 'Brussels - Heart of European Union', false, false),
('vienna.com.rich', 'cities', NULL, 'available', 'Vienna - Imperial elegance and cultural refinement', false, false),
('stockholm.com.rich', 'cities', NULL, 'available', 'Stockholm - Nordic design and innovation', false, false),
('copenhagen.com.rich', 'cities', NULL, 'available', 'Copenhagen - Sustainable living and design excellence', false, false),
('oslo.com.rich', 'cities', NULL, 'available', 'Oslo - Norwegian prosperity and natural beauty', false, false),
('helsinki.com.rich', 'cities', NULL, 'available', 'Helsinki - Nordic design and technology', false, false),
('dublin.com.rich', 'cities', NULL, 'available', 'Dublin - European tech hub and culture', false, false),
('moscow.com.rich', 'cities', NULL, 'available', 'Moscow - Russian power and cultural center', false, false),
('istanbul.com.rich', 'cities', NULL, 'available', 'Istanbul - Bridge between continents and cultures', false, false),
('athens.com.rich', 'cities', NULL, 'available', 'Athens - Ancient heritage and Mediterranean charm', false, false),
('lisbon.com.rich', 'cities', NULL, 'available', 'Lisbon - Atlantic culture and emerging tech scene', false, false),
('porto.com.rich', 'cities', NULL, 'available', 'Porto - Port wine heritage and coastal beauty', false, false),

-- Asia
('tokyo.com.rich', 'cities', NULL, 'available', 'Tokyo - Technology innovation and cultural fusion', true, false),
('shanghai.com.rich', 'cities', NULL, 'available', 'Shanghai - Chinese financial hub and modern marvel', true, false),
('beijing.com.rich', 'cities', NULL, 'available', 'Beijing - Political power and ancient culture', false, false),
('shenzhen.com.rich', 'cities', NULL, 'available', 'Shenzhen - Tech manufacturing and innovation', false, false),
('mumbai.com.rich', 'cities', NULL, 'available', 'Mumbai - Bollywood and Indian financial center', false, false),
('delhi.com.rich', 'cities', NULL, 'available', 'Delhi - Indian capital and historical heritage', false, false),
('bangalore.com.rich', 'cities', NULL, 'available', 'Bangalore - India Silicon Valley and tech talent', false, false),
('seoul.com.rich', 'cities', NULL, 'available', 'Seoul - K-pop culture and technology leader', false, false),
('bangkok.com.rich', 'cities', NULL, 'available', 'Bangkok - Southeast Asian hub and tourism', false, false),
('kualalumpur.com.rich', 'cities', NULL, 'available', 'Kuala Lumpur - Islamic finance and trade center', false, false),
('jakarta.com.rich', 'cities', NULL, 'available', 'Jakarta - Indonesian megacity and commerce', false, false),
('manila.com.rich', 'cities', NULL, 'available', 'Manila - Philippine capital and BPO center', false, false),
('hanoi.com.rich', 'cities', NULL, 'available', 'Hanoi - Vietnamese culture and emerging economy', false, false),
('saigon.com.rich', 'cities', NULL, 'available', 'Ho Chi Minh City - Vietnamese economic engine', false, false),
('taipei.com.rich', 'cities', NULL, 'available', 'Taipei - Tech innovation and Chinese culture', false, false),
('abudhabi.com.rich', 'cities', NULL, 'available', 'Abu Dhabi - UAE capital and sovereign wealth', true, false),
('doha.com.rich', 'cities', NULL, 'available', 'Doha - Qatar wealth and global events', false, false),
('riyadh.com.rich', 'cities', NULL, 'available', 'Riyadh - Saudi capital and Vision 2030', false, false),
('telaviv.com.rich', 'cities', NULL, 'available', 'Tel Aviv - Startup hub and Mediterranean lifestyle', false, false),
('jerusalem.com.rich', 'cities', NULL, 'available', 'Jerusalem - Ancient holy city and history', false, false),

-- Middle East continued
('beirut.com.rich', 'cities', NULL, 'available', 'Beirut - Paris of the Middle East', false, false),
('amman.com.rich', 'cities', NULL, 'available', 'Amman - Jordanian capital and ancient heritage', false, false),
('tehran.com.rich', 'cities', NULL, 'available', 'Tehran - Persian capital and culture', false, false),
('baghdad.com.rich', 'cities', NULL, 'available', 'Baghdad - Ancient Mesopotamian capital', false, false),

-- Africa & Oceania
('cairo.com.rich', 'cities', NULL, 'available', 'Cairo - Ancient pyramids and modern metropolis', false, false),
('capetown.com.rich', 'cities', NULL, 'available', 'Cape Town - African beauty and lifestyle paradise', false, false),
('johannesburg.com.rich', 'cities', NULL, 'available', 'Johannesburg - African financial powerhouse', false, false),
('nairobi.com.rich', 'cities', NULL, 'available', 'Nairobi - East African hub and safari gateway', false, false),
('lagos.com.rich', 'cities', NULL, 'available', 'Lagos - African megacity and entertainment', false, false),
('casablanca.com.rich', 'cities', NULL, 'available', 'Casablanca - Moroccan business and culture', false, false),
('sydney.com.rich', 'cities', NULL, 'available', 'Sydney - Iconic harbor and Australian lifestyle', true, false),
('melbourne.com.rich', 'cities', NULL, 'available', 'Melbourne - Australian culture and livability', false, false),
('auckland.com.rich', 'cities', NULL, 'available', 'Auckland - New Zealand gateway and sailing capital', false, false);

-- Lifestyle & Luxury Segments
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
-- Fashion & Style
('fashion.com.rich', 'lifestyle', NULL, 'available', 'Ultimate fashion industry and luxury style', true, false),
('luxury.com.rich', 'lifestyle', NULL, 'available', 'Premium luxury lifestyle and high-end experiences', true, false),
('couture.com.rich', 'lifestyle', NULL, 'available', 'Haute couture and bespoke fashion excellence', true, false),
('style.com.rich', 'lifestyle', NULL, 'available', 'Personal style and fashion authority', false, false),
('designer.com.rich', 'lifestyle', NULL, 'available', 'Designer brands and exclusive collections', false, false),
('boutique.com.rich', 'lifestyle', NULL, 'available', 'Exclusive boutique shopping and curated fashion', false, false),
('jewelry.com.rich', 'lifestyle', NULL, 'available', 'Fine jewelry and precious gems', true, false),
('diamonds.com.rich', 'lifestyle', NULL, 'available', 'Diamond trade and luxury gemstones', true, false),
('watches.com.rich', 'lifestyle', NULL, 'available', 'Luxury timepieces and haute horlogerie', true, false),
('accessories.com.rich', 'lifestyle', NULL, 'available', 'Premium fashion accessories and lifestyle', false, false),
('handbags.com.rich', 'lifestyle', NULL, 'available', 'Luxury handbag collections and iconic designs', false, false),
('shoes.com.rich', 'lifestyle', NULL, 'available', 'Designer footwear and luxury shoes', false, false),
('sunglasses.com.rich', 'lifestyle', NULL, 'available', 'Premium eyewear and luxury sunglasses', false, false),
('perfume.com.rich', 'lifestyle', NULL, 'available', 'Luxury fragrances and exclusive scents', false, false),
('cosmetics.com.rich', 'lifestyle', NULL, 'available', 'Premium beauty and luxury cosmetics', false, false),
('beauty.com.rich', 'lifestyle', NULL, 'available', 'Beauty industry and premium skincare', false, false),
('skincare.com.rich', 'lifestyle', NULL, 'available', 'Luxury skincare and anti-aging solutions', false, false),

-- Travel & Hospitality
('travel.com.rich', 'lifestyle', NULL, 'available', 'Luxury travel and exclusive experiences', true, false),
('hotels.com.rich', 'lifestyle', NULL, 'available', 'Premium hotels and luxury accommodations', true, false),
('resorts.com.rich', 'lifestyle', NULL, 'available', 'Luxury resort destinations worldwide', false, false),
('villas.com.rich', 'lifestyle', NULL, 'available', 'Private villas and exclusive retreats', false, false),
('yachts.com.rich', 'lifestyle', NULL, 'available', 'Superyachts and luxury marine lifestyle', true, false),
('jets.com.rich', 'lifestyle', NULL, 'available', 'Private jets and aviation luxury', true, false),
('aviation.com.rich', 'lifestyle', NULL, 'available', 'Private aviation and exclusive travel', false, false),
('cruise.com.rich', 'lifestyle', NULL, 'available', 'Luxury cruise experiences and ocean travel', false, false),
('safari.com.rich', 'lifestyle', NULL, 'available', 'Exclusive safari adventures and wildlife', false, false),
('islands.com.rich', 'lifestyle', NULL, 'available', 'Private islands and tropical paradises', true, false),
('beaches.com.rich', 'lifestyle', NULL, 'available', 'World-class beaches and coastal luxury', false, false),
('mountains.com.rich', 'lifestyle', NULL, 'available', 'Alpine luxury and mountain retreats', false, false),
('ski.com.rich', 'lifestyle', NULL, 'available', 'Luxury ski resorts and winter sports', false, false),
('golf.com.rich', 'lifestyle', NULL, 'available', 'Championship golf courses and club memberships', false, false),
('spa.com.rich', 'lifestyle', NULL, 'available', 'Luxury spa treatments and wellness retreats', false, false),
('wellness.com.rich', 'lifestyle', NULL, 'available', 'Premium wellness and holistic health', false, false),

-- Entertainment & Culture
('entertainment.com.rich', 'lifestyle', NULL, 'available', 'Premium entertainment and exclusive events', false, false),
('events.com.rich', 'lifestyle', NULL, 'available', 'Luxury events and exclusive gatherings', false, false),
('concerts.com.rich', 'lifestyle', NULL, 'available', 'VIP concert experiences and backstage access', false, false),
('theatre.com.rich', 'lifestyle', NULL, 'available', 'Premium theatre and performing arts', false, false),
('opera.com.rich', 'lifestyle', NULL, 'available', 'Opera excellence and cultural refinement', false, false),
('ballet.com.rich', 'lifestyle', NULL, 'available', 'Ballet performances and dance excellence', false, false),
('art.com.rich', 'lifestyle', NULL, 'available', 'Fine art collections and gallery access', true, false),
('gallery.com.rich', 'lifestyle', NULL, 'available', 'Art galleries and exclusive exhibitions', false, false),
('auction.com.rich', 'lifestyle', NULL, 'available', 'Premium auctions and collectible assets', false, false),
('collectibles.com.rich', 'lifestyle', NULL, 'available', 'Rare collectibles and investment pieces', false, false),
('wine.com.rich', 'lifestyle', NULL, 'available', 'Fine wine collections and vineyard estates', true, false),
('champagne.com.rich', 'lifestyle', NULL, 'available', 'Premium champagne and celebration lifestyle', false, false),
('cigars.com.rich', 'lifestyle', NULL, 'available', 'Premium cigars and luxury tobacco', false, false),
('whiskey.com.rich', 'lifestyle', NULL, 'available', 'Fine whiskey and rare spirits', false, false),
('spirits.com.rich', 'lifestyle', NULL, 'available', 'Premium spirits and luxury beverages', false, false),
('dining.com.rich', 'lifestyle', NULL, 'available', 'Fine dining and Michelin-star experiences', false, false),
('restaurants.com.rich', 'lifestyle', NULL, 'available', 'Premium restaurants and culinary excellence', false, false),
('chef.com.rich', 'lifestyle', NULL, 'available', 'Celebrity chefs and culinary artistry', false, false),
('gourmet.com.rich', 'lifestyle', NULL, 'available', 'Gourmet cuisine and epicurean experiences', false, false),
('caviar.com.rich', 'lifestyle', NULL, 'available', 'Premium caviar and luxury delicacies', false, false),

-- Sports & Recreation
('sports.com.rich', 'lifestyle', NULL, 'available', 'Premium sports and athletic excellence', false, false),
('racing.com.rich', 'lifestyle', NULL, 'available', 'Motor racing and high-performance automotive', false, false),
('tennis.com.rich', 'lifestyle', NULL, 'available', 'Professional tennis and club memberships', false, false),
('polo.com.rich', 'lifestyle', NULL, 'available', 'Polo excellence and equestrian lifestyle', false, false),
('equestrian.com.rich', 'lifestyle', NULL, 'available', 'Horse breeding and equestrian sports', false, false),
('sailing.com.rich', 'lifestyle', NULL, 'available', 'Luxury sailing and regatta competitions', false, false),
('fishing.com.rich', 'lifestyle', NULL, 'available', 'Sport fishing and exclusive charters', false, false),
('hunting.com.rich', 'lifestyle', NULL, 'available', 'Trophy hunting and exclusive reserves', false, false);

-- Automotive & Transportation
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
('automotive.com.rich', 'automotive', NULL, 'available', 'Luxury automotive industry and high-performance', true, false),
('cars.com.rich', 'automotive', NULL, 'available', 'Premium automobiles and luxury vehicles', true, false),
('supercars.com.rich', 'automotive', NULL, 'available', 'Exotic supercars and hypercar excellence', true, false),
('classic.com.rich', 'automotive', NULL, 'available', 'Classic cars and vintage automobile collections', false, false),
('vintage.com.rich', 'automotive', NULL, 'available', 'Vintage vehicles and automotive heritage', false, false),
('motorsport.com.rich', 'automotive', NULL, 'available', 'Professional motorsport and racing excellence', false, false),
('formula1.com.rich', 'automotive', NULL, 'available', 'Formula 1 racing and automotive technology', false, false),
('motorcycles.com.rich', 'automotive', NULL, 'available', 'Premium motorcycles and luxury bikes', false, false),
('bikes.com.rich', 'automotive', NULL, 'available', 'High-end bicycles and cycling excellence', false, false),
('garage.com.rich', 'automotive', NULL, 'available', 'Premium garages and car collections', false, false),
('collection.com.rich', 'automotive', NULL, 'available', 'Vehicle collections and automotive passion', false, false),
('restoration.com.rich', 'automotive', NULL, 'available', 'Classic car restoration and preservation', false, false),
('customization.com.rich', 'automotive', NULL, 'available', 'Vehicle customization and bespoke builds', false, false),
('tuning.com.rich', 'automotive', NULL, 'available', 'Performance tuning and automotive enhancement', false, false),
('electric.com.rich', 'automotive', NULL, 'available', 'Electric vehicles and sustainable mobility', false, false),
('autonomous.com.rich', 'automotive', NULL, 'available', 'Autonomous vehicles and future transportation', false, false);

-- Real Estate & Property
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
('realestate.com.rich', 'real-estate', NULL, 'available', 'Premium real estate and luxury properties', true, false),
('property.com.rich', 'real-estate', NULL, 'available', 'High-value property investments worldwide', true, false),
('mansions.com.rich', 'real-estate', NULL, 'available', 'Luxury mansions and palatial estates', true, false),
('estates.com.rich', 'real-estate', NULL, 'available', 'Grand estates and historic properties', false, false),
('penthouses.com.rich', 'real-estate', NULL, 'available', 'Exclusive penthouses and sky-high living', false, false),
('condos.com.rich', 'real-estate', NULL, 'available', 'Luxury condominiums and urban living', false, false),
('apartments.com.rich', 'real-estate', NULL, 'available', 'Premium apartments and residential excellence', false, false),
('homes.com.rich', 'real-estate', NULL, 'available', 'Luxury homes and dream residences', false, false),
('waterfront.com.rich', 'real-estate', NULL, 'available', 'Waterfront properties and coastal estates', false, false),
('beachfront.com.rich', 'real-estate', NULL, 'available', 'Beachfront properties and oceanfront living', false, false),
('lakefront.com.rich', 'real-estate', NULL, 'available', 'Lakefront estates and serene retreats', false, false),
('castles.com.rich', 'real-estate', NULL, 'available', 'Historic castles and European grandeur', false, false),
('chateau.com.rich', 'real-estate', NULL, 'available', 'French chateaux and wine estates', false, false),
('palazzo.com.rich', 'real-estate', NULL, 'available', 'Italian palazzos and architectural heritage', false, false),
('development.com.rich', 'real-estate', NULL, 'available', 'Premium property development and construction', false, false),
('architecture.com.rich', 'real-estate', NULL, 'available', 'Architectural excellence and design innovation', false, false),
('interiordesign.com.rich', 'real-estate', NULL, 'available', 'Luxury interior design and home styling', false, false),
('landscape.com.rich', 'real-estate', NULL, 'available', 'Landscape architecture and garden design', false, false),
('furniture.com.rich', 'real-estate', NULL, 'available', 'Luxury furniture and interior collections', false, false),
('decor.com.rich', 'real-estate', NULL, 'available', 'Premium home decor and styling', false, false);

-- Business & Professional Services
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
('business.com.rich', 'business', NULL, 'available', 'Premium business services and excellence', true, false),
('consulting.com.rich', 'business', NULL, 'available', 'Elite consulting and advisory services', false, false),
('advisory.com.rich', 'business', NULL, 'available', 'Strategic advisory and expert guidance', false, false),
('strategy.com.rich', 'business', NULL, 'available', 'Business strategy and growth planning', false, false),
('management.com.rich', 'business', NULL, 'available', 'Executive management and leadership', false, false),
('executive.com.rich', 'business', NULL, 'available', 'Executive services and C-suite solutions', false, false),
('corporate.com.rich', 'business', NULL, 'available', 'Corporate excellence and enterprise solutions', false, false),
('enterprise.com.rich', 'business', NULL, 'available', 'Enterprise-level business services', false, false),
('ventures.com.rich', 'business', NULL, 'available', 'Venture capital and startup investments', false, false),
('capital.com.rich', 'business', NULL, 'available', 'Capital markets and investment excellence', false, false),
('equity.com.rich', 'business', NULL, 'available', 'Private equity and ownership stakes', false, false),
('acquisition.com.rich', 'business', NULL, 'available', 'Mergers and acquisitions expertise', false, false),
('merger.com.rich', 'business', NULL, 'available', 'Corporate mergers and strategic combinations', false, false),
('ipo.com.rich', 'business', NULL, 'available', 'Initial public offerings and market listings', false, false),
('listing.com.rich', 'business', NULL, 'available', 'Stock exchange listings and market access', false, false),
('trading.com.rich', 'business', NULL, 'available', 'Trading excellence and market operations', false, false),
('brokerage.com.rich', 'business', NULL, 'available', 'Premium brokerage and trading services', false, false),
('deals.com.rich', 'business', NULL, 'available', 'Deal-making and transaction excellence', false, false),
('transactions.com.rich', 'business', NULL, 'available', 'High-value transactions and deal flow', false, false),
('networking.com.rich', 'business', NULL, 'available', 'Elite networking and business connections', false, false),
('partnerships.com.rich', 'business', NULL, 'available', 'Strategic partnerships and alliances', false, false),
('alliances.com.rich', 'business', NULL, 'available', 'Business alliances and joint ventures', false, false),
('syndicate.com.rich', 'business', NULL, 'available', 'Investment syndicates and group investments', false, false),
('consortium.com.rich', 'business', NULL, 'available', 'Business consortiums and collective power', false, false),
('holdings.com.rich', 'business', NULL, 'available', 'Holding companies and asset management', false, false),
('portfolio.com.rich', 'business', NULL, 'available', 'Investment portfolios and asset collections', false, false),
('assets.com.rich', 'business', NULL, 'available', 'Asset management and wealth preservation', false, false),
('resources.com.rich', 'business', NULL, 'available', 'Resource allocation and management', false, false),
('commodities.com.rich', 'business', NULL, 'available', 'Commodity trading and resource markets', false, false),
('energy.com.rich', 'business', NULL, 'available', 'Energy sector and power generation', false, false),
('oil.com.rich', 'business', NULL, 'available', 'Oil industry and petroleum excellence', false, false),
('gas.com.rich', 'business', NULL, 'available', 'Natural gas and energy resources', false, false),
('mining.com.rich', 'business', NULL, 'available', 'Mining operations and mineral extraction', false, false),
('metals.com.rich', 'business', NULL, 'available', 'Precious metals and commodity trading', false, false),
('gold.com.rich', 'business', NULL, 'available', 'Gold trading and precious metal investments', true, false),
('silver.com.rich', 'business', NULL, 'available', 'Silver markets and metal trading', false, false),
('platinum.com.rich', 'business', NULL, 'available', 'Platinum trading and rare metals', false, false),
('agriculture.com.rich', 'business', NULL, 'available', 'Agricultural business and farming excellence', false, false),
('farming.com.rich', 'business', NULL, 'available', 'Premium farming and agricultural operations', false, false),
('forestry.com.rich', 'business', NULL, 'available', 'Forestry management and timber resources', false, false),
('timber.com.rich', 'business', NULL, 'available', 'Timber trade and wood products', false, false),
('manufacturing.com.rich', 'business', NULL, 'available', 'Manufacturing excellence and production', false, false),
('production.com.rich', 'business', NULL, 'available', 'Production systems and operational excellence', false, false),
('logistics.com.rich', 'business', NULL, 'available', 'Logistics management and supply chain', false, false),
('supply.com.rich', 'business', NULL, 'available', 'Supply chain and procurement excellence', false, false),
('distribution.com.rich', 'business', NULL, 'available', 'Distribution networks and logistics', false, false),
('shipping.com.rich', 'business', NULL, 'available', 'International shipping and freight', false, false),
('freight.com.rich', 'business', NULL, 'available', 'Freight forwarding and cargo services', false, false),
('warehouse.com.rich', 'business', NULL, 'available', 'Warehouse management and storage', false, false),
('retail.com.rich', 'business', NULL, 'available', 'Premium retail and luxury shopping', false, false),
('wholesale.com.rich', 'business', NULL, 'available', 'Wholesale trade and bulk distribution', false, false),
('import.com.rich', 'business', NULL, 'available', 'Import operations and international trade', false, false),
('export.com.rich', 'business', NULL, 'available', 'Export excellence and global markets', false, false),
('trade.com.rich', 'business', NULL, 'available', 'International trade and commerce', false, false),
('commerce.com.rich', 'business', NULL, 'available', 'E-commerce and digital trading excellence', false, false),
('marketplace.com.rich', 'business', NULL, 'available', 'Premium marketplace and trading platforms', false, false),
('exchange.com.rich', 'business', NULL, 'available', 'Exchange operations and market platforms', false, false);

-- Finance & Investment
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
('finance.com.rich', 'finance', NULL, 'available', 'Financial services and investment excellence', true, false),
('banking.com.rich', 'finance', NULL, 'available', 'Private banking and wealth management', true, false),
('wealth.com.rich', 'finance', NULL, 'available', 'Wealth management and financial prosperity', true, false),
('investment.com.rich', 'finance', NULL, 'available', 'Investment strategies and portfolio management', false, false),
('private.com.rich', 'finance', NULL, 'available', 'Private banking and exclusive services', false, false),
('offshore.com.rich', 'finance', NULL, 'available', 'Offshore banking and asset protection', false, false),
('trust.com.rich', 'finance', NULL, 'available', 'Trust services and estate planning', false, false),
('estate.com.rich', 'finance', NULL, 'available', 'Estate planning and wealth transfer', false, false),
('inheritance.com.rich', 'finance', NULL, 'available', 'Inheritance management and legacy planning', false, false),
('legacy.com.rich', 'finance', NULL, 'available', 'Legacy preservation and generational wealth', false, false),
('foundation.com.rich', 'finance', NULL, 'available', 'Private foundations and philanthropic giving', false, false),
('philanthropy.com.rich', 'finance', NULL, 'available', 'Philanthropic excellence and charitable impact', false, false),
('charity.com.rich', 'finance', NULL, 'available', 'Charitable giving and social impact', false, false),
('endowment.com.rich', 'finance', NULL, 'available', 'Endowment management and perpetual funds', false, false),
('fund.com.rich', 'finance', NULL, 'available', 'Fund management and investment vehicles', false, false),
('hedge.com.rich', 'finance', NULL, 'available', 'Hedge funds and alternative investments', false, false),
('mutual.com.rich', 'finance', NULL, 'available', 'Mutual funds and collective investments', false, false),
('index.com.rich', 'finance', NULL, 'available', 'Index funds and passive investing', false, false),
('etf.com.rich', 'finance', NULL, 'available', 'Exchange-traded funds and diversification', false, false),
('bonds.com.rich', 'finance', NULL, 'available', 'Bond markets and fixed income', false, false),
('stocks.com.rich', 'finance', NULL, 'available', 'Stock market and equity investing', false, false),
('securities.com.rich', 'finance', NULL, 'available', 'Securities trading and investments', false, false),
('derivatives.com.rich', 'finance', NULL, 'available', 'Derivative instruments and hedging', false, false),
('options.com.rich', 'finance', NULL, 'available', 'Options trading and strategies', false, false),
('futures.com.rich', 'finance', NULL, 'available', 'Futures markets and commodity trading', false, false),
('forex.com.rich', 'finance', NULL, 'available', 'Foreign exchange and currency trading', false, false),
('currency.com.rich', 'finance', NULL, 'available', 'Currency markets and exchange trading', false, false),
('crypto.com.rich', 'finance', NULL, 'available', 'Cryptocurrency and blockchain excellence', true, false),
('bitcoin.com.rich', 'finance', NULL, 'available', 'Bitcoin trading and digital gold', true, false),
('blockchain.com.rich', 'finance', NULL, 'available', 'Blockchain technology and DeFi', false, false),
('defi.com.rich', 'finance', NULL, 'available', 'Decentralized finance and crypto banking', false, false),
('nft.com.rich', 'finance', NULL, 'available', 'NFT marketplace and digital collectibles', false, false),
('token.com.rich', 'finance', NULL, 'available', 'Token economics and crypto assets', false, false),
('wallet.com.rich', 'finance', NULL, 'available', 'Crypto wallets and digital asset security', false, false),
('lending.com.rich', 'finance', NULL, 'available', 'Lending services and credit solutions', false, false),
('credit.com.rich', 'finance', NULL, 'available', 'Credit markets and lending excellence', false, false),
('mortgage.com.rich', 'finance', NULL, 'available', 'Mortgage financing and property loans', false, false),
('loan.com.rich', 'finance', NULL, 'available', 'Loan services and financing solutions', false, false),
('financing.com.rich', 'finance', NULL, 'available', 'Financing solutions and capital access', false, false),
('leasing.com.rich', 'finance', NULL, 'available', 'Equipment leasing and asset financing', false, false),
('factoring.com.rich', 'finance', NULL, 'available', 'Invoice factoring and cash flow solutions', false, false),
('insurance.com.rich', 'finance', NULL, 'available', 'Premium insurance and risk management', false, false),
('reinsurance.com.rich', 'finance', NULL, 'available', 'Reinsurance and risk transfer', false, false),
('underwriting.com.rich', 'finance', NULL, 'available', 'Underwriting excellence and risk assessment', false, false),
('actuarial.com.rich', 'finance', NULL, 'available', 'Actuarial services and risk modeling', false, false),
('risk.com.rich', 'finance', NULL, 'available', 'Risk management and mitigation strategies', false, false),
('compliance.com.rich', 'finance', NULL, 'available', 'Regulatory compliance and governance', false, false),
('audit.com.rich', 'finance', NULL, 'available', 'Audit services and financial verification', false, false),
('accounting.com.rich', 'finance', NULL, 'available', 'Accounting excellence and financial reporting', false, false),
('tax.com.rich', 'finance', NULL, 'available', 'Tax planning and optimization strategies', false, false);

-- Technology & Innovation
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
('technology.com.rich', 'technology', NULL, 'available', 'Technology innovation and digital excellence', true, false),
('tech.com.rich', 'technology', NULL, 'available', 'Tech industry and innovation hub', true, false),
('innovation.com.rich', 'technology', NULL, 'available', 'Innovation leadership and breakthrough technology', false, false),
('digital.com.rich', 'technology', NULL, 'available', 'Digital transformation and technology', false, false),
('software.com.rich', 'technology', NULL, 'available', 'Software development and solutions', false, false),
('cloud.com.rich', 'technology', NULL, 'available', 'Cloud computing and infrastructure', false, false),
('saas.com.rich', 'technology', NULL, 'available', 'Software as a Service excellence', false, false),
('platform.com.rich', 'technology', NULL, 'available', 'Platform technology and ecosystems', false, false),
('app.com.rich', 'technology', NULL, 'available', 'Mobile applications and app development', false, false),
('mobile.com.rich', 'technology', NULL, 'available', 'Mobile technology and communications', false, false),
('ai.com.rich', 'technology', NULL, 'available', 'Artificial intelligence and machine learning', true, false),
('machine.com.rich', 'technology', NULL, 'available', 'Machine learning and predictive analytics', false, false),
('robotics.com.rich', 'technology', NULL, 'available', 'Robotics and automation technology', false, false),
('automation.com.rich', 'technology', NULL, 'available', 'Automation solutions and efficiency', false, false),
('iot.com.rich', 'technology', NULL, 'available', 'Internet of Things and connected devices', false, false),
('5g.com.rich', 'technology', NULL, 'available', '5G technology and next-gen connectivity', false, false),
('quantum.com.rich', 'technology', NULL, 'available', 'Quantum computing and advanced technology', false, false),
('biotech.com.rich', 'technology', NULL, 'available', 'Biotechnology and life sciences innovation', false, false),
('nanotech.com.rich', 'technology', NULL, 'available', 'Nanotechnology and materials science', false, false),
('space.com.rich', 'technology', NULL, 'available', 'Space technology and commercial spaceflight', false, false),
('satellite.com.rich', 'technology', NULL, 'available', 'Satellite technology and communications', false, false),
('drone.com.rich', 'technology', NULL, 'available', 'Drone technology and aerial innovation', false, false),
('vr.com.rich', 'technology', NULL, 'available', 'Virtual reality and immersive experiences', false, false),
('ar.com.rich', 'technology', NULL, 'available', 'Augmented reality and mixed reality', false, false),
('metaverse.com.rich', 'technology', NULL, 'available', 'Metaverse platforms and virtual worlds', false, false),
('gaming.com.rich', 'technology', NULL, 'available', 'Gaming industry and esports excellence', false, false),
('esports.com.rich', 'technology', NULL, 'available', 'Professional esports and competitive gaming', false, false),
('streaming.com.rich', 'technology', NULL, 'available', 'Streaming services and content delivery', false, false),
('media.com.rich', 'technology', NULL, 'available', 'Media production and content excellence', false, false),
('content.com.rich', 'technology', NULL, 'available', 'Content creation and digital media', false, false),
('video.com.rich', 'technology', NULL, 'available', 'Video production and streaming technology', false, false),
('music.com.rich', 'technology', NULL, 'available', 'Music industry and streaming excellence', false, false),
('podcast.com.rich', 'technology', NULL, 'available', 'Podcast production and audio content', false, false),
('audio.com.rich', 'technology', NULL, 'available', 'Audio technology and sound engineering', false, false),
('production.com.rich', 'technology', NULL, 'available', 'Production excellence and creative services', false, false),
('studio.com.rich', 'technology', NULL, 'available', 'Studio services and creative production', false, false),
('publishing.com.rich', 'technology', NULL, 'available', 'Digital publishing and content distribution', false, false),
('news.com.rich', 'technology', NULL, 'available', 'News media and journalism excellence', false, false),
('magazine.com.rich', 'technology', NULL, 'available', 'Magazine publishing and editorial content', false, false),
('journal.com.rich', 'technology', NULL, 'available', 'Academic journals and research publishing', false, false),
('research.com.rich', 'technology', NULL, 'available', 'Research excellence and innovation', false, false),
('science.com.rich', 'technology', NULL, 'available', 'Scientific advancement and research', false, false),
('data.com.rich', 'technology', NULL, 'available', 'Data analytics and business intelligence', false, false),
('analytics.com.rich', 'technology', NULL, 'available', 'Analytics platforms and data insights', false, false),
('database.com.rich', 'technology', NULL, 'available', 'Database management and data systems', false, false),
('security.com.rich', 'technology', NULL, 'available', 'Cybersecurity and information protection', false, false),
('cyber.com.rich', 'technology', NULL, 'available', 'Cybersecurity expertise and defense', false, false),
('privacy.com.rich', 'technology', NULL, 'available', 'Privacy protection and data security', false, false),
('network.com.rich', 'technology', NULL, 'available', 'Network infrastructure and connectivity', false, false),
('telecom.com.rich', 'technology', NULL, 'available', 'Telecommunications and connectivity', false, false),
('bandwidth.com.rich', 'technology', NULL, 'available', 'Bandwidth and network capacity', false, false),
('hosting.com.rich', 'technology', NULL, 'available', 'Premium hosting and infrastructure', false, false),
('domain.com.rich', 'technology', NULL, 'available', 'Domain services and internet infrastructure', false, false),
('web.com.rich', 'technology', NULL, 'available', 'Web development and internet services', false, false),
('internet.com.rich', 'technology', NULL, 'available', 'Internet infrastructure and connectivity', false, false),
('email.com.rich', 'technology', NULL, 'available', 'Email services and communication platforms', false, false),
('communication.com.rich', 'technology', NULL, 'available', 'Communication technology and platforms', false, false),
('collaboration.com.rich', 'technology', NULL, 'available', 'Collaboration tools and team platforms', false, false);

-- Health & Wellness
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
('health.com.rich', 'health', NULL, 'available', 'Healthcare excellence and medical services', true, false),
('medical.com.rich', 'health', NULL, 'available', 'Medical services and healthcare innovation', false, false),
('hospital.com.rich', 'health', NULL, 'available', 'Premium hospitals and medical centers', false, false),
('clinic.com.rich', 'health', NULL, 'available', 'Medical clinics and specialized care', false, false),
('surgery.com.rich', 'health', NULL, 'available', 'Surgical excellence and medical procedures', false, false),
('cardiology.com.rich', 'health', NULL, 'available', 'Cardiology expertise and heart health', false, false),
('oncology.com.rich', 'health', NULL, 'available', 'Oncology services and cancer treatment', false, false),
('neurology.com.rich', 'health', NULL, 'available', 'Neurology and brain health excellence', false, false),
('orthopedics.com.rich', 'health', NULL, 'available', 'Orthopedic services and joint care', false, false),
('dentistry.com.rich', 'health', NULL, 'available', 'Premium dentistry and oral health', false, false),
('ophthalmology.com.rich', 'health', NULL, 'available', 'Eye care and vision excellence', false, false),
('dermatology.com.rich', 'health', NULL, 'available', 'Dermatology and skin health', false, false),
('plastic.com.rich', 'health', NULL, 'available', 'Plastic surgery and aesthetic medicine', false, false),
('aesthetic.com.rich', 'health', NULL, 'available', 'Aesthetic treatments and beauty medicine', false, false),
('longevity.com.rich', 'health', NULL, 'available', 'Longevity medicine and anti-aging', false, false),
('antiaging.com.rich', 'health', NULL, 'available', 'Anti-aging treatments and rejuvenation', false, false),
('regenerative.com.rich', 'health', NULL, 'available', 'Regenerative medicine and cell therapy', false, false),
('stemcell.com.rich', 'health', NULL, 'available', 'Stem cell therapy and regeneration', false, false),
('genetics.com.rich', 'health', NULL, 'available', 'Genetic testing and personalized medicine', false, false),
('genomics.com.rich', 'health', NULL, 'available', 'Genomics research and DNA analysis', false, false),
('pharmacy.com.rich', 'health', NULL, 'available', 'Pharmaceutical services and medications', false, false),
('pharmaceutical.com.rich', 'health', NULL, 'available', 'Pharmaceutical industry and drug development', false, false),
('biomedical.com.rich', 'health', NULL, 'available', 'Biomedical engineering and medical devices', false, false),
('diagnostics.com.rich', 'health', NULL, 'available', 'Medical diagnostics and testing', false, false),
('laboratory.com.rich', 'health', NULL, 'available', 'Laboratory services and medical testing', false, false),
('radiology.com.rich', 'health', NULL, 'available', 'Radiology and medical imaging', false, false),
('imaging.com.rich', 'health', NULL, 'available', 'Medical imaging and diagnostic technology', false, false),
('therapy.com.rich', 'health', NULL, 'available', 'Therapeutic services and healing', false, false),
('rehabilitation.com.rich', 'health', NULL, 'available', 'Rehabilitation and recovery services', false, false),
('physiotherapy.com.rich', 'health', NULL, 'available', 'Physiotherapy and physical rehabilitation', false, false),
('chiropractic.com.rich', 'health', NULL, 'available', 'Chiropractic care and spinal health', false, false),
('acupuncture.com.rich', 'health', NULL, 'available', 'Acupuncture and traditional medicine', false, false),
('holistic.com.rich', 'health', NULL, 'available', 'Holistic health and integrative medicine', false, false),
('alternative.com.rich', 'health', NULL, 'available', 'Alternative medicine and natural healing', false, false),
('nutrition.com.rich', 'health', NULL, 'available', 'Nutrition science and dietary excellence', false, false),
('diet.com.rich', 'health', NULL, 'available', 'Diet programs and nutritional guidance', false, false),
('fitness.com.rich', 'health', NULL, 'available', 'Fitness training and wellness programs', false, false),
('gym.com.rich', 'health', NULL, 'available', 'Premium gym facilities and training', false, false),
('training.com.rich', 'health', NULL, 'available', 'Personal training and fitness coaching', false, false),
('yoga.com.rich', 'health', NULL, 'available', 'Yoga instruction and mindfulness', false, false),
('meditation.com.rich', 'health', NULL, 'available', 'Meditation practice and mental wellness', false, false),
('mindfulness.com.rich', 'health', NULL, 'available', 'Mindfulness training and consciousness', false, false),
('mental.com.rich', 'health', NULL, 'available', 'Mental health and psychological wellness', false, false),
('psychology.com.rich', 'health', NULL, 'available', 'Psychology services and mental health', false, false),
('psychiatry.com.rich', 'health', NULL, 'available', 'Psychiatric services and mental healthcare', false, false);

-- Education & Development
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
('education.com.rich', 'education', NULL, 'available', 'Premium education and learning excellence', true, false),
('university.com.rich', 'education', NULL, 'available', 'University education and higher learning', false, false),
('college.com.rich', 'education', NULL, 'available', 'College education and academic excellence', false, false),
('academy.com.rich', 'education', NULL, 'available', 'Academy programs and specialized training', false, false),
('school.com.rich', 'education', NULL, 'available', 'School systems and educational institutions', false, false),
('learning.com.rich', 'education', NULL, 'available', 'Learning platforms and educational technology', false, false),
('elearning.com.rich', 'education', NULL, 'available', 'E-learning and online education', false, false),
('online.com.rich', 'education', NULL, 'available', 'Online education and digital learning', false, false),
('courses.com.rich', 'education', NULL, 'available', 'Professional courses and skill development', false, false),
('training.com.rich', 'education', NULL, 'available', 'Professional training and development', false, false),
('coaching.com.rich', 'education', NULL, 'available', 'Executive coaching and personal development', false, false),
('mentoring.com.rich', 'education', NULL, 'available', 'Mentoring programs and guidance', false, false),
('tutoring.com.rich', 'education', NULL, 'available', 'Premium tutoring and academic support', false, false),
('language.com.rich', 'education', NULL, 'available', 'Language learning and linguistic excellence', false, false),
('mba.com.rich', 'education', NULL, 'available', 'MBA programs and business education', false, false),
('executive.com.rich', 'education', NULL, 'available', 'Executive education and leadership', false, false),
('leadership.com.rich', 'education', NULL, 'available', 'Leadership development and training', false, false),
('development.com.rich', 'education', NULL, 'available', 'Professional development and growth', false, false),
('skills.com.rich', 'education', NULL, 'available', 'Skills training and capability building', false, false),
('certification.com.rich', 'education', NULL, 'available', 'Professional certification and credentials', false, false),
('degree.com.rich', 'education', NULL, 'available', 'Academic degrees and qualifications', false, false),
('masters.com.rich', 'education', NULL, 'available', 'Masters programs and advanced degrees', false, false),
('phd.com.rich', 'education', NULL, 'available', 'PhD programs and doctoral education', false, false),
('doctorate.com.rich', 'education', NULL, 'available', 'Doctorate degrees and research', false, false),
('scholarship.com.rich', 'education', NULL, 'available', 'Scholarship programs and educational funding', false, false),
('grant.com.rich', 'education', NULL, 'available', 'Educational grants and research funding', false, false),
('fellowship.com.rich', 'education', NULL, 'available', 'Fellowship programs and academic support', false, false),
('library.com.rich', 'education', NULL, 'available', 'Library services and knowledge resources', false, false),
('knowledge.com.rich', 'education', NULL, 'available', 'Knowledge management and learning systems', false, false),
('wisdom.com.rich', 'education', NULL, 'available', 'Wisdom cultivation and philosophical learning', false, false);

-- Additional Premium Segments
INSERT INTO premium_domains (fqdn, category, price_usd, status, description, is_featured, show_price) VALUES
-- Legal & Professional
('legal.com.rich', 'business', NULL, 'available', 'Legal services and law firm excellence', false, false),
('law.com.rich', 'business', NULL, 'available', 'Law practice and legal expertise', false, false),
('attorney.com.rich', 'business', NULL, 'available', 'Attorney services and legal counsel', false, false),
('lawyer.com.rich', 'business', NULL, 'available', 'Lawyer expertise and legal representation', false, false),
('litigation.com.rich', 'business', NULL, 'available', 'Litigation services and trial law', false, false),
('arbitration.com.rich', 'business', NULL, 'available', 'Arbitration and dispute resolution', false, false),
('mediation.com.rich', 'business', NULL, 'available', 'Mediation services and conflict resolution', false, false),
('patent.com.rich', 'business', NULL, 'available', 'Patent law and intellectual property', false, false),
('trademark.com.rich', 'business', NULL, 'available', 'Trademark protection and brand law', false, false),
('copyright.com.rich', 'business', NULL, 'available', 'Copyright law and intellectual property', false, false),
('intellectual.com.rich', 'business', NULL, 'available', 'Intellectual property and IP law', false, false),

-- Luxury Lifestyle Continued
('concierge.com.rich', 'lifestyle', NULL, 'available', 'Luxury concierge and lifestyle management', false, false),
('butler.com.rich', 'lifestyle', NULL, 'available', 'Butler services and household management', false, false),
('staff.com.rich', 'lifestyle', NULL, 'available', 'Household staff and domestic services', false, false),
('household.com.rich', 'lifestyle', NULL, 'available', 'Household management and luxury services', false, false),
('membership.com.rich', 'lifestyle', NULL, 'available', 'Exclusive memberships and private clubs', false, false),
('club.com.rich', 'lifestyle', NULL, 'available', 'Private clubs and exclusive access', true, false),
('vip.com.rich', 'lifestyle', NULL, 'available', 'VIP services and premium experiences', true, false),
('exclusive.com.rich', 'lifestyle', NULL, 'available', 'Exclusive access and premium privileges', false, false),
('elite.com.rich', 'lifestyle', NULL, 'available', 'Elite status and premium membership', true, false),
('prestige.com.rich', 'lifestyle', NULL, 'available', 'Prestige brands and luxury excellence', false, false),
('premium.com.rich', 'lifestyle', NULL, 'available', 'Premium quality and excellence', false, false),
('signature.com.rich', 'lifestyle', NULL, 'available', 'Signature experiences and branded excellence', false, false),
('bespoke.com.rich', 'lifestyle', NULL, 'available', 'Bespoke services and customization', false, false),
('custom.com.rich', 'lifestyle', NULL, 'available', 'Custom creations and personalized luxury', false, false),
('personalized.com.rich', 'lifestyle', NULL, 'available', 'Personalized services and tailored experiences', false, false),
('tailor.com.rich', 'lifestyle', NULL, 'available', 'Tailoring excellence and bespoke fashion', false, false),
('craftsmanship.com.rich', 'lifestyle', NULL, 'available', 'Craftsmanship and artisan excellence', false, false),
('artisan.com.rich', 'lifestyle', NULL, 'available', 'Artisan products and handcrafted luxury', false, false),
('heritage.com.rich', 'lifestyle', NULL, 'available', 'Heritage brands and traditional excellence', false, false),
('legacy.com.rich', 'lifestyle', NULL, 'available', 'Legacy preservation and generational value', false, false),
('tradition.com.rich', 'lifestyle', NULL, 'available', 'Traditional craftsmanship and heritage', false, false),
('excellence.com.rich', 'lifestyle', NULL, 'available', 'Excellence in all endeavors and pursuits', false, false),
('perfection.com.rich', 'lifestyle', NULL, 'available', 'Perfection and flawless execution', false, false),
('quality.com.rich', 'lifestyle', NULL, 'available', 'Quality assurance and premium standards', false, false),
('standard.com.rich', 'lifestyle', NULL, 'available', 'Standard-setting excellence and benchmarks', false, false),
('benchmark.com.rich', 'lifestyle', NULL, 'available', 'Benchmark performance and industry leadership', false, false),
('icon.com.rich', 'lifestyle', NULL, 'available', 'Iconic status and legendary excellence', false, false),
('legend.com.rich', 'lifestyle', NULL, 'available', 'Legendary status and timeless excellence', false, false),
('classic.com.rich', 'lifestyle', NULL, 'available', 'Classic elegance and timeless style', false, false),
('timeless.com.rich', 'lifestyle', NULL, 'available', 'Timeless design and eternal elegance', false, false),
('eternal.com.rich', 'lifestyle', NULL, 'available', 'Eternal value and lasting excellence', false, false),
('infinite.com.rich', 'lifestyle', NULL, 'available', 'Infinite possibilities and boundless luxury', false, false),
('limitless.com.rich', 'lifestyle', NULL, 'available', 'Limitless opportunities and boundless success', false, false),
('ultimate.com.rich', 'lifestyle', NULL, 'available', 'Ultimate experiences and supreme luxury', false, false),
('supreme.com.rich', 'lifestyle', NULL, 'available', 'Supreme quality and peak excellence', false, false),
('pinnacle.com.rich', 'lifestyle', NULL, 'available', 'Pinnacle achievement and top-tier excellence', false, false),
('apex.com.rich', 'lifestyle', NULL, 'available', 'Apex performance and peak success', false, false),
('summit.com.rich', 'lifestyle', NULL, 'available', 'Summit achievement and top-level success', false, false),
('zenith.com.rich', 'lifestyle', NULL, 'available', 'Zenith point and ultimate achievement', false, false),
('paramount.com.rich', 'lifestyle', NULL, 'available', 'Paramount importance and supreme value', false, false),
('sovereign.com.rich', 'lifestyle', NULL, 'available', 'Sovereign status and independent wealth', false, false),
('imperial.com.rich', 'lifestyle', NULL, 'available', 'Imperial grandeur and regal excellence', false, false),
('royal.com.rich', 'lifestyle', NULL, 'available', 'Royal treatment and majestic experiences', false, false),
('regal.com.rich', 'lifestyle', NULL, 'available', 'Regal elegance and noble excellence', false, false),
('noble.com.rich', 'lifestyle', NULL, 'available', 'Noble heritage and aristocratic excellence', false, false),
('aristocrat.com.rich', 'lifestyle', NULL, 'available', 'Aristocratic lifestyle and elite society', false, false),
('dynasty.com.rich', 'lifestyle', NULL, 'available', 'Dynasty building and generational wealth', false, false),
('empire.com.rich', 'lifestyle', NULL, 'available', 'Empire building and global influence', false, false),
('kingdom.com.rich', 'lifestyle', NULL, 'available', 'Kingdom creation and domain mastery', false, false),
('crown.com.rich', 'lifestyle', NULL, 'available', 'Crown jewels and supreme excellence', false, false),
('throne.com.rich', 'lifestyle', NULL, 'available', 'Throne position and leadership excellence', false, false),
('palace.com.rich', 'lifestyle', NULL, 'available', 'Palace living and grand residences', false, false),
('manor.com.rich', 'lifestyle', NULL, 'available', 'Manor estates and countryside elegance', false, false),
('villa.com.rich', 'lifestyle', NULL, 'available', 'Villa living and Mediterranean luxury', false, false),
('residence.com.rich', 'lifestyle', NULL, 'available', 'Luxury residences and prestigious addresses', false, false),
('address.com.rich', 'lifestyle', NULL, 'available', 'Prestigious addresses and prime locations', false, false),
('location.com.rich', 'lifestyle', NULL, 'available', 'Prime locations and strategic positioning', false, false),
('destination.com.rich', 'lifestyle', NULL, 'available', 'Destination excellence and travel luxury', false, false),
('paradise.com.rich', 'lifestyle', NULL, 'available', 'Paradise destinations and tropical luxury', false, false),
('haven.com.rich', 'lifestyle', NULL, 'available', 'Haven retreats and safe harbors', false, false),
('sanctuary.com.rich', 'lifestyle', NULL, 'available', 'Sanctuary spaces and peaceful retreats', false, false),
('retreat.com.rich', 'lifestyle', NULL, 'available', 'Retreat experiences and wellness getaways', false, false),
('escape.com.rich', 'lifestyle', NULL, 'available', 'Escape destinations and luxury getaways', false, false),
('getaway.com.rich', 'lifestyle', NULL, 'available', 'Getaway experiences and vacation luxury', false, false),
('vacation.com.rich', 'lifestyle', NULL, 'available', 'Vacation excellence and travel experiences', false, false),
('holiday.com.rich', 'lifestyle', NULL, 'available', 'Holiday celebrations and luxury travel', false, false),
('journey.com.rich', 'lifestyle', NULL, 'available', 'Journey experiences and transformative travel', false, false),
('adventure.com.rich', 'lifestyle', NULL, 'available', 'Adventure travel and experiential luxury', false, false),
('expedition.com.rich', 'lifestyle', NULL, 'available', 'Expedition travel and extreme experiences', false, false),
('exploration.com.rich', 'lifestyle', NULL, 'available', 'Exploration and discovery experiences', false, false),
('discovery.com.rich', 'lifestyle', NULL, 'available', 'Discovery experiences and new horizons', false, false),
('experience.com.rich', 'lifestyle', NULL, 'available', 'Experience design and memorable moments', false, false),
('moment.com.rich', 'lifestyle', NULL, 'available', 'Moment creation and lasting memories', false, false),
('memory.com.rich', 'lifestyle', NULL, 'available', 'Memory making and unforgettable experiences', false, false),
('celebration.com.rich', 'lifestyle', NULL, 'available', 'Celebration planning and special events', false, false),
('occasion.com.rich', 'lifestyle', NULL, 'available', 'Special occasions and milestone events', false, false),
('milestone.com.rich', 'lifestyle', NULL, 'available', 'Milestone celebrations and achievements', false, false),
('achievement.com.rich', 'lifestyle', NULL, 'available', 'Achievement recognition and success', false, false),
('success.com.rich', 'lifestyle', NULL, 'available', 'Success strategies and achievement', true, false),
('victory.com.rich', 'lifestyle', NULL, 'available', 'Victory celebration and winning excellence', false, false),
('triumph.com.rich', 'lifestyle', NULL, 'available', 'Triumph moments and achievement', false, false),
('glory.com.rich', 'lifestyle', NULL, 'available', 'Glory achievement and recognition', false, false),
('honor.com.rich', 'lifestyle', NULL, 'available', 'Honor and integrity excellence', false, false),
('dignity.com.rich', 'lifestyle', NULL, 'available', 'Dignity and respectful excellence', false, false),
('respect.com.rich', 'lifestyle', NULL, 'available', 'Respect and professional excellence', false, false),
('integrity.com.rich', 'lifestyle', NULL, 'available', 'Integrity and ethical excellence', false, false),
('ethics.com.rich', 'lifestyle', NULL, 'available', 'Ethics and moral excellence', false, false),
('values.com.rich', 'lifestyle', NULL, 'available', 'Values-driven excellence and principles', false, false),
('principles.com.rich', 'lifestyle', NULL, 'available', 'Principled leadership and values', false, false),
('philosophy.com.rich', 'lifestyle', NULL, 'available', 'Philosophy and wisdom traditions', false, false),
('vision.com.rich', 'lifestyle', NULL, 'available', 'Vision clarity and strategic foresight', false, false),
('mission.com.rich', 'lifestyle', NULL, 'available', 'Mission-driven excellence and purpose', false, false),
('purpose.com.rich', 'lifestyle', NULL, 'available', 'Purpose-driven life and meaningful impact', false, false),
('passion.com.rich', 'lifestyle', NULL, 'available', 'Passion pursuit and enthusiastic excellence', false, false),
('dream.com.rich', 'lifestyle', NULL, 'available', 'Dream realization and aspiration', false, false),
('aspiration.com.rich', 'lifestyle', NULL, 'available', 'Aspiration achievement and goal pursuit', false, false),
('ambition.com.rich', 'lifestyle', NULL, 'available', 'Ambition and drive for excellence', false, false),
('drive.com.rich', 'lifestyle', NULL, 'available', 'Drive and motivation for success', false, false),
('motivation.com.rich', 'lifestyle', NULL, 'available', 'Motivation and inspiration excellence', false, false),
('inspiration.com.rich', 'lifestyle', NULL, 'available', 'Inspiration and creative excellence', false, false),
('creativity.com.rich', 'lifestyle', NULL, 'available', 'Creativity and innovative thinking', false, false),
('imagination.com.rich', 'lifestyle', NULL, 'available', 'Imagination and creative vision', false, false),
('genius.com.rich', 'lifestyle', NULL, 'available', 'Genius thinking and exceptional intelligence', false, false),
('brilliance.com.rich', 'lifestyle', NULL, 'available', 'Brilliance and exceptional excellence', false, false),
('mastery.com.rich', 'lifestyle', NULL, 'available', 'Mastery achievement and expert excellence', false, false),
('expert.com.rich', 'lifestyle', NULL, 'available', 'Expert knowledge and professional mastery', false, false),
('specialist.com.rich', 'lifestyle', NULL, 'available', 'Specialist expertise and focused excellence', false, false),
('professional.com.rich', 'lifestyle', NULL, 'available', 'Professional services and expert excellence', false, false),
('authority.com.rich', 'lifestyle', NULL, 'available', 'Authority status and expert recognition', false, false),
('influence.com.rich', 'lifestyle', NULL, 'available', 'Influence building and thought leadership', false, false),
('power.com.rich', 'lifestyle', NULL, 'available', 'Power positioning and strategic influence', false, false),
('impact.com.rich', 'lifestyle', NULL, 'available', 'Impact creation and meaningful change', false, false),
('change.com.rich', 'lifestyle', NULL, 'available', 'Change management and transformation', false, false),
('transformation.com.rich', 'lifestyle', NULL, 'available', 'Transformation and personal evolution', false, false),
('evolution.com.rich', 'lifestyle', NULL, 'available', 'Evolution and continuous improvement', false, false),
('growth.com.rich', 'lifestyle', NULL, 'available', 'Growth strategies and expansion', false, false),
('expansion.com.rich', 'lifestyle', NULL, 'available', 'Expansion planning and growth', false, false),
('scale.com.rich', 'lifestyle', NULL, 'available', 'Scale achievement and growth excellence', false, false),
('momentum.com.rich', 'lifestyle', NULL, 'available', 'Momentum building and forward progress', false, false),
('progress.com.rich', 'lifestyle', NULL, 'available', 'Progress tracking and continuous improvement', false, false),
('advancement.com.rich', 'lifestyle', NULL, 'available', 'Advancement and career progression', false, false),
('promotion.com.rich', 'lifestyle', NULL, 'available', 'Promotion and career advancement', false, false),
('career.com.rich', 'lifestyle', NULL, 'available', 'Career excellence and professional growth', false, false),
('opportunity.com.rich', 'lifestyle', NULL, 'available', 'Opportunity recognition and advantage', false, false),
('advantage.com.rich', 'lifestyle', NULL, 'available', 'Competitive advantage and strategic edge', false, false),
('edge.com.rich', 'lifestyle', NULL, 'available', 'Cutting edge innovation and advantage', false, false),
('frontier.com.rich', 'lifestyle', NULL, 'available', 'Frontier exploration and new territories', false, false),
('horizon.com.rich', 'lifestyle', NULL, 'available', 'Horizon expansion and new possibilities', false, false),
('future.com.rich', 'lifestyle', NULL, 'available', 'Future vision and forward thinking', false, false),
('tomorrow.com.rich', 'lifestyle', NULL, 'available', 'Tomorrow planning and future preparation', false, false),
('next.com.rich', 'lifestyle', NULL, 'available', 'Next generation and future excellence', false, false),
('generation.com.rich', 'lifestyle', NULL, 'available', 'Generational wealth and legacy', false, false),
('millennium.com.rich', 'lifestyle', NULL, 'available', 'Millennium achievement and thousand-year vision', false, false),
('century.com.rich', 'lifestyle', NULL, 'available', 'Century-defining excellence and legacy', false, false),
('era.com.rich', 'lifestyle', NULL, 'available', 'Era-defining innovation and transformation', false, false),
('epoch.com.rich', 'lifestyle', NULL, 'available', 'Epoch-making achievements and history', false, false),
('history.com.rich', 'lifestyle', NULL, 'available', 'History creation and legacy building', false, false),
('story.com.rich', 'lifestyle', NULL, 'available', 'Story telling and narrative excellence', false, false),
('narrative.com.rich', 'lifestyle', NULL, 'available', 'Narrative crafting and story power', false, false),
('brand.com.rich', 'lifestyle', NULL, 'available', 'Brand building and identity excellence', false, false),
('identity.com.rich', 'lifestyle', NULL, 'available', 'Identity creation and brand essence', false, false),
('reputation.com.rich', 'lifestyle', NULL, 'available', 'Reputation management and brand excellence', false, false),
('recognition.com.rich', 'lifestyle', NULL, 'available', 'Recognition achievement and brand awareness', false, false),
('awareness.com.rich', 'lifestyle', NULL, 'available', 'Awareness building and market presence', false, false),
('presence.com.rich', 'lifestyle', NULL, 'available', 'Presence establishment and brand power', false, false),
('prominence.com.rich', 'lifestyle', NULL, 'available', 'Prominence achievement and visibility', false, false),
('visibility.com.rich', 'lifestyle', NULL, 'available', 'Visibility enhancement and market presence', false, false),
('exposure.com.rich', 'lifestyle', NULL, 'available', 'Exposure maximization and reach', false, false),
('reach.com.rich', 'lifestyle', NULL, 'available', 'Reach expansion and audience growth', false, false),
('audience.com.rich', 'lifestyle', NULL, 'available', 'Audience building and engagement', false, false),
('engagement.com.rich', 'lifestyle', NULL, 'available', 'Engagement strategies and connection', false, false),
('connection.com.rich', 'lifestyle', NULL, 'available', 'Connection building and relationship excellence', false, false),
('relationship.com.rich', 'lifestyle', NULL, 'available', 'Relationship management and networking', false, false),
('network.com.rich', 'lifestyle', NULL, 'available', 'Network building and strategic connections', false, false),
('circle.com.rich', 'lifestyle', NULL, 'available', 'Inner circle access and exclusive network', false, false),
('society.com.rich', 'lifestyle', NULL, 'available', 'High society and elite social circles', false, false),
('elite.com.rich', 'lifestyle', NULL, 'available', 'Elite membership and exclusive access', false, false),
('select.com.rich', 'lifestyle', NULL, 'available', 'Select membership and curated excellence', false, false),
('curated.com.rich', 'lifestyle', NULL, 'available', 'Curated experiences and selective excellence', false, false),
('refined.com.rich', 'lifestyle', NULL, 'available', 'Refined tastes and sophisticated excellence', false, false),
('sophisticated.com.rich', 'lifestyle', NULL, 'available', 'Sophisticated lifestyle and cultured excellence', false, false),
('cultured.com.rich', 'lifestyle', NULL, 'available', 'Cultured living and refined sophistication', false, false),
('elegant.com.rich', 'lifestyle', NULL, 'available', 'Elegant style and graceful excellence', false, false),
('graceful.com.rich', 'lifestyle', NULL, 'available', 'Graceful living and elegant excellence', false, false),
('distinguished.com.rich', 'lifestyle', NULL, 'available', 'Distinguished status and notable excellence', false, false),
('notable.com.rich', 'lifestyle', NULL, 'available', 'Notable achievement and recognition', false, false),
('remarkable.com.rich', 'lifestyle', NULL, 'available', 'Remarkable experiences and exceptional excellence', false, false),
('exceptional.com.rich', 'lifestyle', NULL, 'available', 'Exceptional quality and outstanding excellence', false, false),
('extraordinary.com.rich', 'lifestyle', NULL, 'available', 'Extraordinary experiences and remarkable excellence', false, false),
('phenomenal.com.rich', 'lifestyle', NULL, 'available', 'Phenomenal achievement and extraordinary success', false, false),
('spectacular.com.rich', 'lifestyle', NULL, 'available', 'Spectacular experiences and amazing excellence', false, false),
('magnificent.com.rich', 'lifestyle', NULL, 'available', 'Magnificent experiences and grand excellence', false, false),
('splendid.com.rich', 'lifestyle', NULL, 'available', 'Splendid living and magnificent excellence', false, false),
('superb.com.rich', 'lifestyle', NULL, 'available', 'Superb quality and excellent excellence', false, false),
('outstanding.com.rich', 'lifestyle', NULL, 'available', 'Outstanding achievement and exceptional excellence', false, false),
('premier.com.rich', 'lifestyle', NULL, 'available', 'Premier status and first-class excellence', false, false),
('first.com.rich', 'lifestyle', NULL, 'available', 'First-class experiences and premier excellence', false, false),
('finest.com.rich', 'lifestyle', NULL, 'available', 'Finest quality and supreme excellence', false, false),
('best.com.rich', 'lifestyle', NULL, 'available', 'Best-in-class and top-tier excellence', true, false),
('top.com.rich', 'lifestyle', NULL, 'available', 'Top-tier status and highest excellence', false, false),
('leading.com.rich', 'lifestyle', NULL, 'available', 'Leading position and market excellence', false, false),
('foremost.com.rich', 'lifestyle', NULL, 'available', 'Foremost position and primary excellence', false, false),
('primary.com.rich', 'lifestyle', NULL, 'available', 'Primary position and leading excellence', false, false),
('principal.com.rich', 'lifestyle', NULL, 'available', 'Principal status and main excellence', false, false),
('main.com.rich', 'lifestyle', NULL, 'available', 'Main position and central excellence', false, false),
('central.com.rich', 'lifestyle', NULL, 'available', 'Central position and core excellence', false, false),
('core.com.rich', 'lifestyle', NULL, 'available', 'Core values and essential excellence', false, false),
('essential.com.rich', 'lifestyle', NULL, 'available', 'Essential services and fundamental excellence', false, false),
('fundamental.com.rich', 'lifestyle', NULL, 'available', 'Fundamental principles and core excellence', false, false),
('foundation.com.rich', 'lifestyle', NULL, 'available', 'Foundation building and fundamental excellence', false, false),
('cornerstone.com.rich', 'lifestyle', NULL, 'available', 'Cornerstone positioning and fundamental excellence', false, false),
('pillar.com.rich', 'lifestyle', NULL, 'available', 'Pillar status and foundational excellence', false, false),
('anchor.com.rich', 'lifestyle', NULL, 'available', 'Anchor position and stability excellence', false, false),
('foundation.com.rich', 'lifestyle', NULL, 'available', 'Foundation excellence and core principles', false, false);

-- Total domains inserted: 900+
-- This provides a comprehensive premium domain catalog across all major categories
