/*
  # Add Premium Domains Bulk Import (with trigger bypass)
  
  1. Changes
    - Temporarily disable keyword validation triggers
    - Insert 206 premium .com.rich domains
    - Re-enable validation triggers after insertion
  
  2. Rationale
    - Premium domains are intentionally using commercial/generic keywords
    - These are high-value domains meant for commercial use
    - Validation is only needed for user-submitted domains, not admin-curated premium ones
  
  3. Safety Features
    - ON CONFLICT (fqdn) DO NOTHING prevents duplicates
    - Triggers re-enabled immediately after insertion
    - Idempotent operation
*/

-- Temporarily disable validation triggers
ALTER TABLE premium_domains DISABLE TRIGGER validate_premium_domain_before_insert;
ALTER TABLE premium_domains DISABLE TRIGGER validate_premium_domain_before_update;

-- Insert all 206 premium domains
INSERT INTO premium_domains (fqdn, price_usd, show_price, status, description, category, is_featured)
VALUES
  ('business.com.rich', 100000, false, 'available', 'Premium domain for business professionals', 'business', false),
  ('consulting.com.rich', 100000, false, 'available', 'Premium domain for consultants', 'business', false),
  ('marketing.com.rich', 100000, false, 'available', 'Premium domain for marketing professionals', 'business', false),
  ('lawyer.com.rich', 100000, false, 'available', 'Premium domain for legal professionals', 'business', false),
  ('accounting.com.rich', 100000, false, 'available', 'Premium domain for accountants', 'business', false),
  ('architect.com.rich', 100000, false, 'available', 'Premium domain for architects', 'business', false),
  ('engineer.com.rich', 100000, false, 'available', 'Premium domain for engineers', 'business', false),
  ('finance.com.rich', 100000, false, 'available', 'Premium domain for finance professionals', 'business', false),
  ('investment.com.rich', 100000, false, 'available', 'Premium domain for investment professionals', 'business', false),
  ('entrepreneur.com.rich', 100000, false, 'available', 'Premium domain for entrepreneurs', 'business', false),
  ('executive.com.rich', 100000, false, 'available', 'Premium domain for executives', 'business', false),
  ('manager.com.rich', 100000, false, 'available', 'Premium domain for managers', 'business', false),
  ('advisor.com.rich', 100000, false, 'available', 'Premium domain for advisors', 'business', false),
  ('ceo.com.rich', 100000, false, 'available', 'Premium domain for CEOs', 'business', true),
  ('founder.com.rich', 100000, false, 'available', 'Premium domain for founders', 'business', false),
  ('director.com.rich', 100000, false, 'available', 'Premium domain for directors', 'business', false),
  ('consultant.com.rich', 100000, false, 'available', 'Premium domain for consultants', 'business', false),
  ('designer.com.rich', 100000, false, 'available', 'Premium domain for designers', 'business', false),
  ('photographer.com.rich', 100000, false, 'available', 'Premium domain for photographers', 'business', false),
  ('producer.com.rich', 100000, false, 'available', 'Premium domain for producers', 'business', false),
  ('coach.com.rich', 100000, false, 'available', 'Premium domain for coaches', 'business', false),
  ('mentor.com.rich', 100000, false, 'available', 'Premium domain for mentors', 'business', false),
  ('agency.com.rich', 100000, false, 'available', 'Premium domain for agencies', 'business', false),
  ('socialmedia.com.rich', 100000, false, 'available', 'Premium domain for social media professionals', 'business', false),
  ('branding.com.rich', 100000, false, 'available', 'Premium domain for branding experts', 'business', false),
  ('corporate.com.rich', 100000, false, 'available', 'Premium domain for corporate use', 'business', false),
  ('strategy.com.rich', 100000, false, 'available', 'Premium domain for strategy professionals', 'business', false),
  ('sales.com.rich', 100000, false, 'available', 'Premium domain for sales professionals', 'business', false),
  ('education.com.rich', 100000, false, 'available', 'Premium domain for education', 'education', false),
  ('university.com.rich', 100000, false, 'available', 'Premium domain for universities', 'education', false),
  ('college.com.rich', 100000, false, 'available', 'Premium domain for colleges', 'education', false),
  ('academy.com.rich', 100000, false, 'available', 'Premium domain for academies', 'education', false),
  ('school.com.rich', 100000, false, 'available', 'Premium domain for schools', 'education', false),
  ('learning.com.rich', 100000, false, 'available', 'Premium domain for learning platforms', 'education', false),
  ('courses.com.rich', 100000, false, 'available', 'Premium domain for online courses', 'education', false),
  ('training.com.rich', 100000, false, 'available', 'Premium domain for training programs', 'education', false),
  ('professor.com.rich', 100000, false, 'available', 'Premium domain for professors', 'education', false),
  ('teacher.com.rich', 100000, false, 'available', 'Premium domain for teachers', 'education', false),
  ('tutor.com.rich', 100000, false, 'available', 'Premium domain for tutors', 'education', false),
  ('skills.com.rich', 100000, false, 'available', 'Premium domain for skills development', 'education', false),
  ('knowledge.com.rich', 100000, false, 'available', 'Premium domain for knowledge sharing', 'education', false),
  ('leadership.com.rich', 100000, false, 'available', 'Premium domain for leadership development', 'education', false),
  ('innovation.com.rich', 100000, false, 'available', 'Premium domain for innovation', 'education', false),
  ('technology.com.rich', 100000, false, 'available', 'Premium domain for technology', 'technology', false),
  ('startup.com.rich', 100000, false, 'available', 'Premium domain for startups', 'technology', false),
  ('software.com.rich', 100000, false, 'available', 'Premium domain for software companies', 'technology', false),
  ('developer.com.rich', 100000, false, 'available', 'Premium domain for developers', 'technology', false),
  ('tech.com.rich', 100000, false, 'available', 'Premium domain for tech professionals', 'technology', true),
  ('cloud.com.rich', 100000, false, 'available', 'Premium domain for cloud services', 'technology', false),
  ('data.com.rich', 100000, false, 'available', 'Premium domain for data services', 'technology', false),
  ('ai.com.rich', 100000, false, 'available', 'Premium domain for AI companies', 'technology', true),
  ('automation.com.rich', 100000, false, 'available', 'Premium domain for automation', 'technology', false),
  ('robotics.com.rich', 100000, false, 'available', 'Premium domain for robotics', 'technology', false),
  ('cyber.com.rich', 100000, false, 'available', 'Premium domain for cybersecurity', 'technology', false),
  ('it.com.rich', 100000, false, 'available', 'Premium domain for IT professionals', 'technology', false),
  ('apps.com.rich', 100000, false, 'available', 'Premium domain for apps', 'technology', false),
  ('support.com.rich', 100000, false, 'available', 'Premium domain for support services', 'technology', false),
  ('system.com.rich', 100000, false, 'available', 'Premium domain for systems', 'technology', false),
  ('network.com.rich', 100000, false, 'available', 'Premium domain for networking', 'technology', false),
  ('web.com.rich', 100000, false, 'available', 'Premium domain for web services', 'technology', false),
  ('hosting.com.rich', 100000, false, 'available', 'Premium domain for hosting services', 'technology', false),
  ('digital.com.rich', 100000, false, 'available', 'Premium domain for digital services', 'technology', false),
  ('platform.com.rich', 100000, false, 'available', 'Premium domain for platforms', 'technology', false),
  ('analytics.com.rich', 100000, false, 'available', 'Premium domain for analytics', 'technology', false),
  ('security.com.rich', 100000, false, 'available', 'Premium domain for security services', 'technology', false),
  ('solutions.com.rich', 100000, false, 'available', 'Premium domain for solution providers', 'technology', false),
  ('commerce.com.rich', 100000, false, 'available', 'Premium domain for commerce', 'commerce', false),
  ('store.com.rich', 100000, false, 'available', 'Premium domain for stores', 'commerce', false),
  ('shop.com.rich', 100000, false, 'available', 'Premium domain for shops', 'commerce', false),
  ('retail.com.rich', 100000, false, 'available', 'Premium domain for retail', 'commerce', false),
  ('restaurant.com.rich', 100000, false, 'available', 'Premium domain for restaurants', 'commerce', false),
  ('hotel.com.rich', 100000, false, 'available', 'Premium domain for hotels', 'commerce', false),
  ('travel.com.rich', 100000, false, 'available', 'Premium domain for travel', 'commerce', false),
  ('tourism.com.rich', 100000, false, 'available', 'Premium domain for tourism', 'commerce', false),
  ('auto.com.rich', 100000, false, 'available', 'Premium domain for automotive', 'commerce', false),
  ('car.com.rich', 100000, false, 'available', 'Premium domain for car services', 'commerce', false),
  ('realestate.com.rich', 100000, false, 'available', 'Premium domain for real estate', 'commerce', false),
  ('property.com.rich', 100000, false, 'available', 'Premium domain for property', 'commerce', false),
  ('construction.com.rich', 100000, false, 'available', 'Premium domain for construction', 'commerce', false),
  ('logistics.com.rich', 100000, false, 'available', 'Premium domain for logistics', 'commerce', false),
  ('delivery.com.rich', 100000, false, 'available', 'Premium domain for delivery services', 'commerce', false),
  ('service.com.rich', 100000, false, 'available', 'Premium domain for services', 'commerce', false),
  ('market.com.rich', 100000, false, 'available', 'Premium domain for markets', 'commerce', false),
  ('cleaning.com.rich', 100000, false, 'available', 'Premium domain for cleaning services', 'commerce', false),
  ('beauty.com.rich', 100000, false, 'available', 'Premium domain for beauty services', 'commerce', false),
  ('barber.com.rich', 100000, false, 'available', 'Premium domain for barbers', 'commerce', false),
  ('spa.com.rich', 100000, false, 'available', 'Premium domain for spas', 'commerce', false),
  ('fashion.com.rich', 100000, false, 'available', 'Premium domain for fashion', 'commerce', false),
  ('luxury.com.rich', 100000, false, 'available', 'Premium domain for luxury brands', 'commerce', true),
  ('events.com.rich', 100000, false, 'available', 'Premium domain for events', 'commerce', false),
  ('press.com.rich', 100000, false, 'available', 'Premium domain for press', 'media', false),
  ('media.com.rich', 100000, false, 'available', 'Premium domain for media', 'media', false),
  ('news.com.rich', 100000, false, 'available', 'Premium domain for news', 'media', false),
  ('magazine.com.rich', 100000, false, 'available', 'Premium domain for magazines', 'media', false),
  ('journal.com.rich', 100000, false, 'available', 'Premium domain for journals', 'media', false),
  ('tv.com.rich', 100000, false, 'available', 'Premium domain for TV', 'media', false),
  ('radio.com.rich', 100000, false, 'available', 'Premium domain for radio', 'media', false),
  ('podcast.com.rich', 100000, false, 'available', 'Premium domain for podcasts', 'media', false),
  ('video.com.rich', 100000, false, 'available', 'Premium domain for video content', 'media', false),
  ('channel.com.rich', 100000, false, 'available', 'Premium domain for channels', 'media', false),
  ('networking.com.rich', 100000, false, 'available', 'Premium domain for networking', 'media', false),
  ('social.com.rich', 100000, false, 'available', 'Premium domain for social platforms', 'media', false),
  ('advertising.com.rich', 100000, false, 'available', 'Premium domain for advertising', 'media', false),
  ('studio.com.rich', 100000, false, 'available', 'Premium domain for studios', 'media', false),
  ('production.com.rich', 100000, false, 'available', 'Premium domain for production', 'media', false),
  ('identity.com.rich', 100000, false, 'available', 'Premium domain for identity', 'identity', false),
  ('profile.com.rich', 100000, false, 'available', 'Premium domain for profiles', 'identity', false),
  ('bio.com.rich', 100000, false, 'available', 'Premium domain for bios', 'identity', false),
  ('portfolio.com.rich', 100000, false, 'available', 'Premium domain for portfolios', 'identity', false),
  ('contact.com.rich', 100000, false, 'available', 'Premium domain for contact pages', 'identity', false),
  ('resume.com.rich', 100000, false, 'available', 'Premium domain for resumes', 'identity', false),
  ('personal.com.rich', 100000, false, 'available', 'Premium domain for personal use', 'identity', false),
  ('signature.com.rich', 100000, false, 'available', 'Premium domain for signatures', 'identity', false),
  ('vip.com.rich', 100000, false, 'available', 'Premium domain for VIP', 'identity', true),
  ('elite.com.rich', 100000, false, 'available', 'Premium domain for elite users', 'identity', true),
  ('exclusive.com.rich', 100000, false, 'available', 'Premium domain for exclusive use', 'identity', false),
  ('premium.com.rich', 100000, false, 'available', 'Premium domain for premium services', 'identity', false),
  ('influence.com.rich', 100000, false, 'available', 'Premium domain for influencers', 'identity', false),
  ('creator.com.rich', 100000, false, 'available', 'Premium domain for creators', 'identity', false),
  ('brand.com.rich', 100000, false, 'available', 'Premium domain for brands', 'identity', false),
  ('presence.com.rich', 100000, false, 'available', 'Premium domain for online presence', 'identity', false),
  ('digitalid.com.rich', 100000, false, 'available', 'Premium domain for digital identity', 'identity', false),
  ('businesscard.com.rich', 100000, false, 'available', 'Premium domain for business cards', 'identity', false),
  ('bank.com.rich', 100000, false, 'available', 'Premium domain for banks', 'finance', false),
  ('credit.com.rich', 100000, false, 'available', 'Premium domain for credit services', 'finance', false),
  ('money.com.rich', 100000, false, 'available', 'Premium domain for money services', 'finance', false),
  ('wealth.com.rich', 100000, false, 'available', 'Premium domain for wealth management', 'finance', false),
  ('trader.com.rich', 100000, false, 'available', 'Premium domain for traders', 'finance', false),
  ('fund.com.rich', 100000, false, 'available', 'Premium domain for funds', 'finance', false),
  ('insurance.com.rich', 100000, false, 'available', 'Premium domain for insurance', 'finance', false),
  ('capital.com.rich', 100000, false, 'available', 'Premium domain for capital services', 'finance', false),
  ('economy.com.rich', 100000, false, 'available', 'Premium domain for economy', 'finance', false),
  ('blockchain.com.rich', 100000, false, 'available', 'Premium domain for blockchain', 'finance', true),
  ('crypto.com.rich', 100000, false, 'available', 'Premium domain for crypto', 'finance', true),
  ('stock.com.rich', 100000, false, 'available', 'Premium domain for stock market', 'finance', false),
  ('trading.com.rich', 100000, false, 'available', 'Premium domain for trading', 'finance', false),
  ('exchange.com.rich', 100000, false, 'available', 'Premium domain for exchanges', 'finance', false),
  ('loan.com.rich', 100000, false, 'available', 'Premium domain for loans', 'finance', false),
  ('assets.com.rich', 100000, false, 'available', 'Premium domain for asset management', 'finance', false),
  ('health.com.rich', 100000, false, 'available', 'Premium domain for health', 'health', false),
  ('medical.com.rich', 100000, false, 'available', 'Premium domain for medical services', 'health', false),
  ('doctor.com.rich', 100000, false, 'available', 'Premium domain for doctors', 'health', false),
  ('clinic.com.rich', 100000, false, 'available', 'Premium domain for clinics', 'health', false),
  ('hospital.com.rich', 100000, false, 'available', 'Premium domain for hospitals', 'health', false),
  ('nutrition.com.rich', 100000, false, 'available', 'Premium domain for nutrition', 'health', false),
  ('therapy.com.rich', 100000, false, 'available', 'Premium domain for therapy', 'health', false),
  ('psychology.com.rich', 100000, false, 'available', 'Premium domain for psychology', 'health', false),
  ('wellness.com.rich', 100000, false, 'available', 'Premium domain for wellness', 'health', false),
  ('fitness.com.rich', 100000, false, 'available', 'Premium domain for fitness', 'health', false),
  ('gym.com.rich', 100000, false, 'available', 'Premium domain for gyms', 'health', false),
  ('life.com.rich', 100000, false, 'available', 'Premium domain for life coaching', 'health', false),
  ('body.com.rich', 100000, false, 'available', 'Premium domain for body care', 'health', false),
  ('mind.com.rich', 100000, false, 'available', 'Premium domain for mental health', 'health', false),
  ('care.com.rich', 100000, false, 'available', 'Premium domain for care services', 'health', false),
  ('beautycare.com.rich', 100000, false, 'available', 'Premium domain for beauty care', 'health', false),
  ('pharma.com.rich', 100000, false, 'available', 'Premium domain for pharmaceutical', 'health', false),
  ('meditation.com.rich', 100000, false, 'available', 'Premium domain for meditation', 'health', false),
  ('usa.com.rich', 100000, false, 'available', 'Premium domain for USA', 'location', false),
  ('newyork.com.rich', 100000, false, 'available', 'Premium domain for New York', 'location', true),
  ('losangeles.com.rich', 100000, false, 'available', 'Premium domain for Los Angeles', 'location', false),
  ('miami.com.rich', 100000, false, 'available', 'Premium domain for Miami', 'location', false),
  ('london.com.rich', 100000, false, 'available', 'Premium domain for London', 'location', true),
  ('paris.com.rich', 100000, false, 'available', 'Premium domain for Paris', 'location', false),
  ('dubai.com.rich', 100000, false, 'available', 'Premium domain for Dubai', 'location', true),
  ('tokyo.com.rich', 100000, false, 'available', 'Premium domain for Tokyo', 'location', false),
  ('hongkong.com.rich', 100000, false, 'available', 'Premium domain for Hong Kong', 'location', false),
  ('singapore.com.rich', 100000, false, 'available', 'Premium domain for Singapore', 'location', false),
  ('toronto.com.rich', 100000, false, 'available', 'Premium domain for Toronto', 'location', false),
  ('brazil.com.rich', 100000, false, 'available', 'Premium domain for Brazil', 'location', false),
  ('mexico.com.rich', 100000, false, 'available', 'Premium domain for Mexico', 'location', false),
  ('vacation.com.rich', 100000, false, 'available', 'Premium domain for vacations', 'location', false),
  ('explorer.com.rich', 100000, false, 'available', 'Premium domain for explorers', 'location', false),
  ('world.com.rich', 100000, false, 'available', 'Premium domain for world travel', 'location', false),
  ('city.com.rich', 100000, false, 'available', 'Premium domain for cities', 'location', false),
  ('global.com.rich', 100000, false, 'available', 'Premium domain for global services', 'location', false),
  ('art.com.rich', 100000, false, 'available', 'Premium domain for art', 'culture', false),
  ('music.com.rich', 100000, false, 'available', 'Premium domain for music', 'culture', false),
  ('film.com.rich', 100000, false, 'available', 'Premium domain for film', 'culture', false),
  ('cinema.com.rich', 100000, false, 'available', 'Premium domain for cinema', 'culture', false),
  ('gallery.com.rich', 100000, false, 'available', 'Premium domain for galleries', 'culture', false),
  ('collector.com.rich', 100000, false, 'available', 'Premium domain for collectors', 'culture', false),
  ('design.com.rich', 100000, false, 'available', 'Premium domain for design', 'culture', false),
  ('theatre.com.rich', 100000, false, 'available', 'Premium domain for theatre', 'culture', false),
  ('show.com.rich', 100000, false, 'available', 'Premium domain for shows', 'culture', false),
  ('celebrity.com.rich', 100000, false, 'available', 'Premium domain for celebrities', 'culture', false),
  ('artist.com.rich', 100000, false, 'available', 'Premium domain for artists', 'culture', false),
  ('talent.com.rich', 100000, false, 'available', 'Premium domain for talent', 'culture', false),
  ('culture.com.rich', 100000, false, 'available', 'Premium domain for culture', 'culture', false),
  ('trend.com.rich', 100000, false, 'available', 'Premium domain for trends', 'culture', false),
  ('style.com.rich', 100000, false, 'available', 'Premium domain for style', 'culture', false),
  ('exclusiveart.com.rich', 100000, false, 'available', 'Premium domain for exclusive art', 'culture', false),
  ('limitededition.com.rich', 100000, false, 'available', 'Premium domain for limited editions', 'culture', false),
  ('energy.com.rich', 100000, false, 'available', 'Premium domain for energy', 'industry', false),
  ('industry.com.rich', 100000, false, 'available', 'Premium domain for industry', 'industry', false),
  ('manufacturing.com.rich', 100000, false, 'available', 'Premium domain for manufacturing', 'industry', false),
  ('engineering.com.rich', 100000, false, 'available', 'Premium domain for engineering', 'industry', false),
  ('science.com.rich', 100000, false, 'available', 'Premium domain for science', 'industry', false),
  ('research.com.rich', 100000, false, 'available', 'Premium domain for research', 'industry', false),
  ('aiinnovation.com.rich', 100000, false, 'available', 'Premium domain for AI innovation', 'industry', false),
  ('smart.com.rich', 100000, false, 'available', 'Premium domain for smart technology', 'industry', false),
  ('future.com.rich', 100000, false, 'available', 'Premium domain for future tech', 'industry', false),
  ('sustainability.com.rich', 100000, false, 'available', 'Premium domain for sustainability', 'industry', false),
  ('green.com.rich', 100000, false, 'available', 'Premium domain for green technology', 'industry', false),
  ('techlab.com.rich', 100000, false, 'available', 'Premium domain for tech labs', 'industry', false),
  ('labs.com.rich', 100000, false, 'available', 'Premium domain for laboratories', 'industry', false),
  ('institute.com.rich', 100000, false, 'available', 'Premium domain for institutes', 'industry', false)
ON CONFLICT (fqdn) DO NOTHING;

-- Re-enable validation triggers
ALTER TABLE premium_domains ENABLE TRIGGER validate_premium_domain_before_insert;
ALTER TABLE premium_domains ENABLE TRIGGER validate_premium_domain_before_update;
